### ISSUE TITLE
Errno::EBADF: Bad file descriptor with parallel_tests gem

### ISSUE THREAD

**Issue by chtitux** [Shopify/bootsnap#104]
Bootsnap works very well on my project, but when I run the specs with the [parallel_tests](https://github.com/grosser/parallel_tests) gem, I get for about **half** of the runs a `Errno::EBADF: Bad file descriptor` error:

~~~
$ PARALLEL_TEST_PROCESSORS=8
$ bin/rake parallel:setup
rake aborted!
Errno::EBADF: Bad file descriptor
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/my-project/lib/payments.rb:29:in `<main>'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/my-project/config/initializers/lib.rb:21:in `<main>'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/my-project/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => ct:db:role:create => environment
(See full trace by running task with --trace)
~~~

Gems used:
* activerecord (5.1.4)
* bootsnap (1.1.5)
* parallel (1.12.0)
* parallel_tests (2.15.0)
* rails (5.1.4)

I can't reproduce on my laptop, but it fails on our Docker Gitlab runner that launch the tests.

**Comment by burke** [comment]
Could you try again with bootsnap 1.1.6.beta2? It won't fix the problem, but it will give a more helpful exception message that will pinpoint the library call generating the failure, which I hope will help with debugging.

**Comment by chtitux** [comment]
Thank you very much for your patch and your beta release!

Here is the message I get with bootsnap 1.1.6beta2:
~~~
bin/rake parallel:setup
rake aborted!
Errno::EBADF: Bad file descriptor - bs_fetch:fetch_cached_data:read
/usr/local/bundle/gems/bootsnap-1.1.6.beta2/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
/usr/local/bundle/gems/bootsnap-1.1.6.beta2/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/usr/local/bundle/gems/bootsnap-1.1.6.beta2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/bootsnap-1.1.6.beta2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
…
[same stuff]
~~~

**Comment by burke** [comment]
Ok, I found -- at least -- *a* problem. Please try again with `1.1.6.beta3`.

**Comment by burke** [comment]
FWIW there was a logic bug in handling the result of `open(2)` on the cache file: https://github.com/Shopify/bootsnap/commit/c2cf10bbd2bfbc47de7515a5765a29e2de97bad6 .

Probably you have another error happening but being masked as this `EBADF`, and I bet it's either `EPERM` or `ENOSPC`.

**Comment by chtitux** [comment]
I can't reproduce the error with `1.1.6.beta3`.

I consider this issue as solved and will close it. Thank you very much for your help!

By the way, do you consider we can use `1.1.6.beta3` in production? As this version fixes our issue, I'd like to keep it in our Gemfile.

**Comment by burke** [comment]
Yes, you can absolutely use 1.1.6.beta3. I will re-release it as 1.1.6 some time this week.
