### ISSUE TITLE
`binwrite': "\xDE" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by gencer** [Shopify/bootsnap#111]
I start to get this error on Windows using bash/cmd. Same project has no this issue on Linux.

This happens whenever I execute **any** command (rake/rails)

I first suspected that one of my file is encoded in wrong charset but with some tools, after checking, cannot find any.

```
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:75:in `binwrite': "\xDE" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:75:in `dump_data'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:152:in `unshift_paths_locked'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:98:in `block in unshift_paths'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:98:in `synchronize'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/cache.rb:98:in `unshift_paths'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/change_observer.rb:27:in `block in register'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/application.rb:330:in `add_lib_to_load_path!'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/application.rb:94:in `inherited'
        from config/application.rb:23:in `<module:Endpoint>'
        from config/application.rb:22:in `<top (required)>'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/command/actions.rb:17:in `require_application_and_environment!'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/command/base.rb:65:in `perform'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/command.rb:46:in `invoke'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<top (required)>'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
        from bin/rails:9:in `<main>'
``

**Comment by gencer** [comment]
Additional Notes:

* Commenting bootsnap setup fix my issue. I believe somewhere at bootsnap cause this error on windows only.
* Rails 5.2 and last stable version of bootsnap used without any additional bootsnap config (all default)

**Comment by johnnyshields** [comment]
having same issue

**Comment by daniel-rikowski** [comment]
Same here.

Using `mode: ...` with `File`/`IO` has an unexpected side effect: It sets the external encoding to `Encoding.default_external` (even when `binwrite` is used)

Look at this:

```ruby
File.open('output.txt', 'w') do |f| 
  puts f.external_encoding.inspect
end
=> nil
```

vs.

```ruby
File.open('output.txt', mode: File::Constants::CREAT) do |f| 
  puts f.external_encoding.inspect
end
=> CP850
```

Forcing the encoding back to `nil` doesn't work, but using `Encoding::BINARY` does.

(IMHO this is a Ruby bug/inconsistency, because using `binmode` does set the encoding to binary, so one expects using `binwrite` to have the same effect...)

**Workaround for Bootsnap**

There are two ways to fix this in `lib/bootsnap/load_path_cache/store.rb`, in the `dump_data` method.

Change:
```ruby
File.binwrite(tmp, MessagePack.dump(@data), mode: exclusive_write)
```    
into either:
```ruby
File.binwrite(tmp, MessagePack.dump(@data), mode: exclusive_write, encoding: Encoding::BINARY)
```    

or:
```ruby
File.binwrite(tmp, MessagePack.dump(@data), mode: exclusive_write | File::Constants::BINARY)
```

**Comment by burke** [comment]
Ohh, I can kind of see how this would happen, with windows managing binary/text in the fd mode.
