### ISSUE TITLE
 Bootsnap::LoadPathCache::Store::NestedTransactionError

### ISSUE THREAD

**Issue by jimchild49** [Shopify/bootsnap#119]
I added bootsnap gem recently to one of my local app, and while the local server was running I went and watched some videos, when I came back to the app and clicked a link I've got  an error (I did no thing everything was running correctly)

Bootsnap::LoadPathCache::Store::NestedTransactionError

it says the error is coming from here : 
```
      def transaction
        raise NestedTransactionError if @in_txn
        @in_txn = true
        yield
      ensure
```

**Comment by KenkenIchimura** [comment]
me too!

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by KenkenIchimura** [comment]
**Versions** 
bootsnap1.3.2
ruby 2.5.1
Rails 5.2.1

**server/config/boot.rb**

```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.

```






**Here is an error message on ReactNative Debugger.**
```
YellowBox.js:67 Possible Unhandled Promise Rejection (id: 10):
TypeError: Network request failed
TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:27971:18)
    at XMLHttpRequest.dispatchEvent (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:29256:27)
    at XMLHttpRequest.setReadyState (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:29009:20)
    at XMLHttpRequest.__didCompleteResponse (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:28836:16)
    at blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:28946:47
    at RCTDeviceEventEmitter.emit (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:4538:37)
    at MessageQueue.__callFunction (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:2608:44)
    at blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:2385:17
    at MessageQueue.__guard (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:2561:13)
    at MessageQueue.callFunctionReturnFlushedQueue (blob:file:///be1668be-e3b0-4547-8aee-f37374691cfb:2384:14)

```﻿

​

**Here is an error message on my terminal.**
```
#<Bootsnap::LoadPathCache::Store::NestedTransactionError: Bootsnap::LoadPathCache::Store::NestedTransactionError>
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/store.rb:43:in `transaction'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:130:in `push_paths_locked'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:113:in `block in reinitialize'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:107:in `synchronize'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:107:in `reinitialize'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:46:in `find'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails.rb:53:in `backtrace_cleaner'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:257:in `env_config'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:694:in `build_request'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:592:in `build_request'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:523:in `call'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/newrelic_rpm-5.3.0.346/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
2018-09-11 10:08:22 +0900: Rack app error handling request { GET /v1/clips }
#<LoadError: cannot load such file -- rails/backtrace_cleaner>
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails.rb:53:in `backtrace_cleaner'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:257:in `env_config'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:694:in `build_request'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:592:in `build_request'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:523:in `call'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/newrelic_rpm-5.3.0.346/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by rafaelfranca** [comment]
Is this a new application or an existing application? Because I can't reproduce this error in a new application.

**Comment by inkstak** [comment]
I've got the same error, randomly, since some days.

This often happens after starting a new development server.
I'll request a first page and all assets provided by sprocket present in the HTML page will fail to load due to this same exception.
After reloading the page, it can work or not.
I didn't succeed to reproduce every time.

It never happens on production.
My colleague, who is working on the same project, never occured the same exception.
He works on Linux, I'm on Mac OS

The backtrace is the same as provided by @KenkenIchimura

**Comment by simonx1** [comment]
Try to remove `tmp/cache` dir. It helped for me (the problem occured after the gem update).

**Comment by amandarebecca89** [comment]
this is what worked for me,  i thought i would comment!
`rake db:schema:dump` and then i ran `rake db:migrate`

**Comment by knightq** [comment]
It happens to me when I switch from a Rails 5.1.7 branch of my application to a branch with the previous version (RoR 4.2.7).
The problem seems related to cookies (maybe session?) since if I force a cache refresh request (Cmd + Shift + R on my Mac), the problem disappears.
