### ISSUE TITLE
Iseq caching changes Regexp encoding and prevents Rubocop from working

### ISSUE THREAD

**Issue by dannyfallon** [Shopify/bootsnap#125]
If Rubocop is used when Bootsnap is enabled with `compile_cache_iseq` it starts throwing
exceptions if the file it is linting has multibyte/emoji characters. These exceptions do not 
occur if Rubocop is run without Bootsnap (i.e. via a freshly generated binstub).

This problem does not exist on OS X/Darwin and cropped up when we added Bootsnap and tested
via CircleCi and Docker. To that end I've created a brand new Rails 5 app with a `Dockerfile`
and `docker-compose` over at https://github.com/dannyfallon/bootsnap-rubocop-iseq that can
be used to reproduce (follow README instructions).

The TL;dr is this does not work:

### application_controller.rb
```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  POSITIVE_RESPONSES = %w[yes 👍].freeze
  NEGATIVE_RESPONSES = %w[no 👎].freeze
end
```

### bin/rubocop

```
#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"
require_relative("../config/boot") # Make Rubocop aware of Bootsnap

load Gem.bin_path("rubocop", "rubocop")
```

### Without `compile_cache_iseq`

```
# bin/rubocop -ld app/controllers/application_controller.rb
For /myapp: configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/default.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/enabled.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/disabled.yml
Inspecting 1 file
Scanning /myapp/app/controllers/application_controller.rb
.
```

### With `compile_cache_iseq`
```
# bin/rubocop -ld app/controllers/application_controller.rb
For /myapp: configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/default.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/enabled.yml
Inheriting configuration from /usr/local/bundle/gems/rubocop-0.52.1/config/disabled.yml
Inspecting 1 file
Scanning /myapp/app/controllers/application_controller.rb
An error occurred while Lint/PercentStringArray cop was inspecting /myapp/app/controllers/application_controller.rb:4:23.
incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:67:in `gsub'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:67:in `block in contains_quotes_or_commas?'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:63:in `any?'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:63:in `contains_quotes_or_commas?'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:38:in `on_percent_literal'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/mixin/percent_literal.rb:18:in `process'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:34:in `on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:109:in `with_cop_error_handling'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:43:in `block in on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:101:in `block in on_send'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:99:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:99:in `each_with_index'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:99:in `on_send'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_send'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:77:in `on_casgn'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_casgn'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `block in on_begin'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `on_begin'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:88:in `on_class'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_class'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:12:in `walk'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:114:in `investigate'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:102:in `offenses'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:258:in `inspect_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `loop'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:111:in `block in file_offenses'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:121:in `file_offense_cache'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:109:in `file_offenses'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:100:in `process_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `reduce'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each_inspected_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:67:in `inspect_files'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:39:in `run'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:150:in `execute_runner'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:78:in `execute_runners'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:38:in `run'
/usr/local/bundle/gems/rubocop-0.52.1/bin/rubocop:13:in `block in <main>'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/rubocop-0.52.1/bin/rubocop:12:in `<main>'
/usr/local/bundle/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/usr/local/bundle/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
bin/rubocop:19:in `<main>'
An error occurred while Lint/PercentStringArray cop was inspecting /myapp/app/controllers/application_controller.rb:5:23.
incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:67:in `gsub'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:67:in `block in contains_quotes_or_commas?'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:63:in `any?'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:63:in `contains_quotes_or_commas?'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:38:in `on_percent_literal'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/mixin/percent_literal.rb:18:in `process'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/lint/percent_string_array.rb:34:in `on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:109:in `with_cop_error_handling'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:43:in `block in on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `on_array'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:101:in `block in on_send'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:99:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:99:in `each_with_index'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:99:in `on_send'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_send'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:77:in `on_casgn'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_casgn'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `block in on_begin'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:49:in `on_begin'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:88:in `on_class'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:48:in `on_class'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:12:in `walk'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:114:in `investigate'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:102:in `offenses'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:258:in `inspect_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `loop'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:111:in `block in file_offenses'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:121:in `file_offense_cache'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:109:in `file_offenses'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:100:in `process_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `reduce'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each_inspected_file'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:67:in `inspect_files'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/runner.rb:39:in `run'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:150:in `execute_runner'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:78:in `execute_runners'
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/cli.rb:38:in `run'
/usr/local/bundle/gems/rubocop-0.52.1/bin/rubocop:13:in `block in <main>'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/rubocop-0.52.1/bin/rubocop:12:in `<main>'
/usr/local/bundle/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/usr/local/bundle/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
bin/rubocop:19:in `<main>'
.

1 file inspected, no offenses detected

2 errors occurred:
An error occurred while Lint/PercentStringArray cop was inspecting /myapp/app/controllers/application_controller.rb:4:23.
An error occurred while Lint/PercentStringArray cop was inspecting /myapp/app/controllers/application_controller.rb:5:23.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.52.1 (using Parser 2.4.0.2, running on ruby 2.3.3 x86_64-linux)
Finished in 0.19560604798607528 seconds
```

**Comment by dannyfallon** [comment]
I dug into this a tiny bit more and modified the problematic code in the Rubocop `Lint/PercentStringArray` cop to output what encodings it thinks it has:

```
        def contains_quotes_or_commas?(node)
          node.values.any? do |value|
            literal = scrub_string(value.children.first.to_s)
            puts "Literal encoding: #{literal.encoding}"
            regexp = Regexp.new(/[^\p{Alnum}]/)
            puts "Regexp encoding: #{regexp.encoding}"
            # To avoid likely false positives (e.g. a single ' or ")
            next if literal.gsub(regexp, '').empty?

            QUOTES_AND_COMMAS.any? { |pat| literal =~ pat }
          end
        end
```

### without `compile_cache_iseq`
```
Literal encoding: UTF-8
Regexp encoding: UTF-8
Literal encoding: UTF-8
Regexp encoding: UTF-8
Literal encoding: UTF-8
Regexp encoding: UTF-8
Literal encoding: UTF-8
Regexp encoding: UTF-8
```

### with `compile_cache_iseq`
```
Literal encoding: UTF-8
Regexp encoding: ASCII-8BIT

Literal encoding: UTF-8
Regexp encoding: ASCII-8BIT

Literal encoding: UTF-8
Regexp encoding: ASCII-8BIT

Literal encoding: UTF-8
Regexp encoding: ASCII-8BIT
```

I don't know where the encoding is coming from 🤔

Take the following code:

```ruby
thumbs_up = Conversation::POSITIVE_RESPONSES.last; puts thumbs_up; puts thumbs_up.encoding;regexp = /[^\p{Alnum}]/; puts regexp.encoding; thumbs_up.gsub(regexp,'')
👍
UTF-8
UTF-8
=> ""
```

Wrapping it in some RubyVM calls to `compile` (not `compile_from_file`) and make it eval:

```ruby
code = "thumbs_up = Conversation::POSITIVE_RESPONSES.last; puts thumbs_up; puts thumbs_up.encoding;regexp = /[^\p{Alnum}]/; puts regexp.encoding; thumbs_up.gsub(regexp,'')"
RubyVM::InstructionSequence.compile(code).eval
👍
UTF-8
US-ASCII
=> ""

And add in a to/from binary transformation:

```ruby
code = "thumbs_up = Conversation::POSITIVE_RESPONSES.last; puts thumbs_up; puts thumbs_up.encoding;regexp = /[^\p{Alnum}]/;puts regexp.encoding; thumbs_up.gsub(regexp,'')"
=> "thumbs_up = Conversation::POSITIVE_RESPONSES.last; puts thumbs_up; puts thumbs_up.encoding;regexp = /[^p{Alnum}]/;puts regexp.encoding; thumbs_up.gsub(regexp,'')"
RubyVM::InstructionSequence.load_from_binary(RubyVM::InstructionSequence.compile(code).to_binary).eval
👍
UTF-8
US-ASCII
=> ""
```

Here's a simpler example of Iseq compilation being lossy:

```
/[^\p{Alnum}]/.fixed_encoding?
=> true
/[^\p{Alnum}]/.encoding
=> #<Encoding:UTF-8>
RubyVM::InstructionSequence.compile("/[^\p{Alnum}]/.fixed_encoding?").eval
=> false
RubyVM::InstructionSequence.compile("/[^\p{Alnum}]/.encoding").eval
=> #<Encoding:US-ASCII>
```

Here's a potential solution I can submit to Rubocop:

```
RubyVM::InstructionSequence.compile("/[^\p{Alnum}]/u.fixed_encoding?").eval
=> true
RubyVM::InstructionSequence.compile("/[^\p{Alnum}]/u.encoding").eval
=> #<Encoding:UTF-8>
```

I'd be interested in knowing why we get ASCII-8BIT from Bootsnap and US-ASCII via a REPL and in your thoughts on whether or not I should file a Ruby bug for this?

**Comment by dannyfallon** [comment]
With a plain IRB session on the Ruby container I ran `/[^\p{Alnum}]/.encoding` and got `ASCII-8BIT` but on Darwin I got `UTF-8`. This led me to the solution of this problem...

I burned a freaking tonne of time on this all because the Ruby Docker image defaults `LANG to C`. It needs to be changed to `LANG=C.UTF-8` as per [the instructions](https://hub.docker.com/_/ruby/) on the Docker Hub 🤦‍♂️ 

I'm still considering if iseq compilation losing the encoding is something I can file against MRI but for now this is a complete non-issue and was a result of bad environment
