### ISSUE TITLE
Bootsnap fails while RSpec is running, with error: "No such device or address - bs_fetch:open_cache_file:open"

### ISSUE THREAD

**Issue by bpina** [Shopify/bootsnap#133]
During RSpec test runs, I am seeing a Bootsnap related error that is making the issue hard to track down. I am assuming the error is being caused by an underlying problem, but I am unable to move forward with the information I am provided here, as I can not identify any possible solutions.

I am running RSpec using Ruby 2.5.0 on an Ubuntu 17.10 system using ext4.

```
	36: from /home/brian/.rbenv/versions/2.5.0/bin/rspec:23:in `<main>'
	35: from /home/brian/.rbenv/versions/2.5.0/bin/rspec:23:in `load'
	34: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
	33: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	32: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	31: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
	30: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
	29: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
	28: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
	27: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
	26: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:175:in `block in finish'
	25: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
	24: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `each'
	23: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:in `block in notify'
	22: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
	21: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
	20: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each_with_index'
	19: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each'
	18: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
	17: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:200:in `fully_formatted'
	16: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:78:in `fully_formatted'
	15: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:86:in `fully_formatted_lines'
	14: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:240:in `formatted_message_and_backtrace'
	13: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:34:in `colorized_message_lines'
	12: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:149:in `failure_lines'
	11: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:149:in `tap'
	10: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:150:in `block in failure_lines'
	 9: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:163:in `failure_slash_error_lines'
	 8: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb:218:in `read_failed_lines'
	 7: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/snippet_extractor.rb:30:in `extract_expression_lines_at'
	 6: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/snippet_extractor.rb:18:in `source_from_file'
	 5: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/world.rb:135:in `source_from_file'
	 4: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-support-3.7.1/lib/rspec/support.rb:19:in `block in define_optimized_require_for_rspec'
	 3: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-support-3.7.1/lib/rspec/support.rb:28:in `block in <module:Support>'
	 2: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-support-3.7.1/lib/rspec/support.rb:28:in `require_relative'
	 1: from /home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/home/brian/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch': No such device or address - bs_fetch:open_cache_file:open (Errno::ENXIO)
```

**Comment by bpina** [comment]
After temporarily peeling Bootsnap out of the project, I was able to identify the underlying cause of the issue:
```
Errno::EMFILE:
       Too many open files #...
```

The problem was ultimately related to Ubuntu specific settings for controlling the maximum number of file descriptors.
