### ISSUE TITLE
Ruby master is broken with bootsnap

### ISSUE THREAD

**Issue by Fudoshiki** [Shopify/bootsnap#139]
This related to ruby
with https://github.com/ruby/ruby/commit/6679ffd3b5a60ebc13fdefeff6d066b43854029b

```bash
$ rails s
/Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:68: [BUG] Segmentation fault at 0x0000000000000018
ruby 2.6.0dev (2018-03-11 trunk 62719) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0038 p:---- s:0201 e:000200 CFUNC  :extname
c:0037 p:0019 s:0196 e:000195 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:68
c:0036 p:0023 s:0187 e:000186 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18
c:0035 p:0052 s:0181 e:000180 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27
c:0034 p:0009 s:0175 e:000174 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:28
c:0033 p:0049 s:0172 e:000171 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:24
c:0032 p:0011 s:0166 e:000165 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:28
c:0031 p:0034 s:0160 e:000159 TOP    /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/railties/lib/rails/command.rb:8 [FINISH]
c:0030 p:---- s:0157 e:000156 CFUNC  :require
c:0029 p:0013 s:0152 e:000151 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19
c:0028 p:0005 s:0149 e:000148 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0027 p:0023 s:0140 e:000139 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18
c:0026 p:0052 s:0134 e:000133 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27
c:0025 p:0009 s:0128 e:000127 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:28
c:0024 p:0049 s:0125 e:000124 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:24
c:0023 p:0011 s:0119 e:000118 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:28
c:0022 p:0006 s:0113 e:000112 TOP    /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/railties/lib/rails/commands.rb:3 [FINISH]
c:0021 p:---- s:0108 e:000107 CFUNC  :require
c:0020 p:0013 s:0103 e:000102 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19
c:0019 p:0005 s:0100 e:000099 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0018 p:0023 s:0091 e:000090 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18
c:0017 p:0052 s:0085 e:000084 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27
c:0016 p:0009 s:0079 e:000078 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:28
c:0015 p:0049 s:0076 e:000075 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:24
c:0014 p:0011 s:0070 e:000069 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/bundler/gems/rails-58eda3cfd8b6/activesupport/lib/active_support/dependencies.rb:28
c:0013 p:0053 s:0064 e:000063 TOP    /Users/fudoshiki/Repository/Fudoshiki/Honshu/bin/rails:11 [FINISH]
c:0012 p:---- s:0060 e:000059 CFUNC  :load
c:0011 p:0134 s:0055 e:000054 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/rails.rb:28
c:0010 p:0009 s:0050 e:000049 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/command.rb:7
c:0009 p:0014 s:0045 e:000044 METHOD /Users/fudoshiki/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client.rb:30
c:0008 p:0293 s:0039 e:000038 TOP    /Users/fudoshiki/.rvm/gems/ruby-head/gems/spring-2.0.2/bin/spring:49 [FINISH]
c:0007 p:---- s:0033 e:000032 CFUNC  :load
c:0006 p:0163 s:0028 e:000027 TOP    /Users/fudoshiki/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/binstub.rb:31 [FINISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :require
c:0004 p:0129 s:0017 e:000016 TOP    /Users/fudoshiki/Repository/Fudoshiki/Honshu/bin/spring:16 [FINISH]
c:0003 p:---- s:0012 e:000011 CFUNC  :load
c:0002 p:0018 s:0007 E:000688 EVAL   bin/rails:5 [FINISH]
c:0001 p:0000 s:0003 E:001ba0 (none) [FINISH]
```
https://bugs.ruby-lang.org/issues/14596

**Comment by burke** [comment]
relevant: https://github.com/Shopify/bootsnap/issues/132

**Comment by Fudoshiki** [comment]
1rst run `rails s`, `spring` stopped

```bash
$ rails s
Traceback (most recent call last):
  36: from bin/rails:5:in `<main>'
  35: from bin/rails:5:in `load'
  34: from /Users/fudoshiki/Repository/Fudoshiki/Honshu/bin/spring:16:in `<top (required)>'
  33: from /Users/fudoshiki/Repository/Fudoshiki/Honshu/bin/spring:16:in `require'
  32: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
  31: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
  30: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
  29: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
  28: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
  27: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
  26: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
  25: from /Users/fudoshiki/Repository/Fudoshiki/Honshu/bin/rails:11:in `<top (required)>'
  24: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:283:in `require'
  23: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
  22: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
  21: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
  20: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
  19: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  18: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `block in require_with_bootsnap_lfi'
  17: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
  16: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/commands.rb:3:in `<main>'
  15: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:283:in `require'
  14: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
  13: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
  12: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
  11: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
  10: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
   9: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `block in require_with_bootsnap_lfi'
   8: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
   7: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/command.rb:8:in `<main>'
   6: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:283:in `require'
   5: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
   4: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
   3: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
   2: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
   1: from /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:68:in `register'
/Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:68:in `extname': path name contains null byte (ArgumentError)
^C^D
```

stop and run again 

```bash
$ rails s
/Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/cache.rb:59: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.0dev (2018-03-13 trunk 62740) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0072 p:0045 s:0378 e:000377 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/cache.rb:59 [FINISH]
c:0071 p:---- s:0374 e:000373 CFUNC  :synchronize
c:0070 p:0069 s:0370 e:000369 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/cache.rb:50
c:0069 p:0039 s:0365 e:000364 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26
c:0068 p:0009 s:0359 e:000358 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0067 p:0049 s:0356 e:000355 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:24
c:0066 p:0011 s:0350 e:000349 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0065 p:0034 s:0344 e:000343 TOP    /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/engine.rb:7 [FINISH]
c:0064 p:---- s:0341 e:000340 CFUNC  :require
c:0063 p:0013 s:0336 e:000335 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19
c:0062 p:0005 s:0333 e:000332 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0061 p:0023 s:0324 e:000323 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18
c:0060 p:0052 s:0318 e:000317 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27
c:0059 p:0009 s:0312 e:000311 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0058 p:0049 s:0309 e:000308 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:24
c:0057 p:0011 s:0303 e:000302 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0056 p:0055 s:0297 e:000296 TOP    /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/application.rb:10 [FINISH]
c:0055 p:---- s:0294 e:000293 CFUNC  :require
c:0054 p:0013 s:0289 e:000288 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19
c:0053 p:0005 s:0286 e:000285 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0052 p:0023 s:0277 e:000276 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18
c:0051 p:0052 s:0271 e:000270 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27
c:0050 p:0009 s:0265 e:000264 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0049 p:0049 s:0262 e:000261 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:24
c:0048 p:0011 s:0256 e:000255 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0047 p:0062 s:0250 e:000249 TOP    /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails.rb:14 [FINISH]
c:0046 p:---- s:0247 e:000246 CFUNC  :require
c:0045 p:0013 s:0242 e:000241 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19
c:0044 p:0005 s:0239 e:000238 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0043 p:0023 s:0230 e:000229 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18
c:0042 p:0052 s:0224 e:000223 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27
c:0041 p:0009 s:0218 e:000217 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0040 p:0049 s:0215 e:000214 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:24
c:0039 p:0011 s:0209 e:000208 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0038 p:0027 s:0203 e:000202 TOP    /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/commands/server/server_command.r [FINISH]
c:0037 p:---- s:0200 e:000199 CFUNC  :require
c:0036 p:0013 s:0195 e:000194 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19
c:0035 p:0005 s:0192 e:000191 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0034 p:0023 s:0183 e:000182 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18
c:0033 p:0052 s:0177 e:000176 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27
c:0032 p:0009 s:0171 e:000170 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0031 p:0049 s:0168 e:000167 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:24
c:0030 p:0011 s:0162 e:000161 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/activesupport/lib/active_support/dependencies.rb:28
c:0029 p:0052 s:0156 e:000155 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/command/behavior.rb:44 [FINISH]
c:0028 p:---- s:0150 e:000149 CFUNC  :each
c:0027 p:0009 s:0146 e:000145 BLOCK  /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/command/behavior.rb:40 [FINISH]
c:0026 p:---- s:0142 e:000141 CFUNC  :each
c:0025 p:0014 s:0138 e:000137 METHOD /Users/fudoshiki/.rvm/gems/ruby-head@Honshu/bundler/gems/rails-3c9edcffb60b/railties/lib/rails/command/behavior.rb:39
```

**Comment by Fudoshiki** [comment]
https://github.com/ruby/ruby/commit/6cd5db8904379eeb3f80998814e028b6f1adc6a8 works
