### ISSUE TITLE
Cannot start rails server if load path cache is enabled

### ISSUE THREAD

**Issue by bmulholland** [Shopify/bootsnap#159]
If load path cache is enabled and I try to start `rails server` then I get an error `undefined method 'formatter' for nil:NilClass (NoMethodError)` in the `log_to_stdout` method of `rails/commands/server` (full stack trace below).

After much digging, this seems to be because the `require config/environment` line in `config.ru` doesn't actually require the file and thus the application is not initialized (causing Rails.logger to be nil). That happens because `LoadPathCache` has `config/environment` marked as loaded, though it's obviously not or the application would be initialized.

I tried to debug deeper to see why it thinks the file has already been loaded, but the caching starts to get way over my head around that point :)

Stack trace:

```
% be rails s
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.3-compliant syntax, but you are running 2.4.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> Booting Puma
=> Rails 4.2.10 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/server.rb:143:in `log_to_stdout': undefined method `formatter' for nil:NilClass (NoMethodError)
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/server.rb:79:in `start'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<main>'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from /Users/bmulholland/dev/coupa_clm/bin/rails:9:in `<top (required)>'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /Users/bmulholland/dev/coupa_clm/bin/spring:15:in `require'
        from /Users/bmulholland/dev/coupa_clm/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

**Comment by burke** [comment]
Does this happen on the latest version?

**Comment by bmulholland** [comment]
Yes

```
/Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/server.rb:143:in `log_to_stdout': undefined method `formatter' for nil:NilClass (NoMethodError)
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/server.rb:79:in `start'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<main>'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from /Users/bmulholland/dev/coupa_clm/bin/rails:9:in `<top (required)>'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /Users/bmulholland/.rvm/gems/ruby-2.4.2@contractually/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /Users/bmulholland/dev/coupa_clm/bin/spring:15:in `require'
        from /Users/bmulholland/dev/coupa_clm/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

**Comment by bmulholland** [comment]
I tried upgrading bootsnap to the latest on another rails app used at our company and have the same issue there.

**Comment by rafaelfranca** [comment]
Is your `Rails.logger` set to `nil` for some reason? Because that is the reason why it is failing.

**Comment by rafaelfranca** [comment]
oh, just saw the explanation in the description.

**Comment by burke** [comment]
Cleaning up old issues. We've changed some things since last year that would likely affect this. If it's still an issue and bothering you on the latest version, please do reopen.
