### ISSUE TITLE
Second load always results in: ArgumentError (msgpack) negative array size (or size too big)

### ISSUE THREAD

**Issue by SleeplessByte** [Shopify/bootsnap#187]
**Ruby**: 2.4.0
**Bootsnap**: 1.3.1
**Platform**: Windows 10

I don't know exactly when this broke or how to reproduce this behaviour in a clean project, but hopefully someone has seen this before. 

On running `rails test` (or `rails c`) the second boot now always results in
```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/msgpack-1.2.4-x64-mingw32/lib/msgpack.rb:34:in
`full_unpack': negative array size (or size too big) (ArgumentError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/msgpack-1.2.4-x64-mingw32/lib/msgp
ack.rb:34:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_p
ath_cache/store.rb:62:in `load_data'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_p
ath_cache/store.rb:16:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_p
ath_cache.rb:28:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_p
ath_cache.rb:28:in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap.rb:24:
in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/setup.
rb:33:in `<top (required)>'
        from D:/Users/Derk-Jan/Documents/GitHub/<project>/config/boot.rb:4:in `requi
        from D:/Users/Derk-Jan/Documents/GitHub/<project>/config/boot.rb:4:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
```

Naturally, deleting `tmp/bootsnap-load-path-cache` or running without bootsnap solves the issue. It worked fine before.

**Comment by SleeplessByte** [comment]
We now also see this on our CI, occasionally, which runs on debian.

**Comment by SleeplessByte** [comment]
Thanks @burke. Not sure if this happened due to _upgrades_ as it failed after manually deleting and NOT updating bundle.

Anyway, clear always works well enough.
