### ISSUE TITLE
lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- <myfile> (LoadError)

### ISSUE THREAD

**Issue by janpio** [Shopify/bootsnap#190]
Hey,

I'm trying to implement bootsnap for [fastlane](https://github.com/fastlane/fastlane). Unfortunately, as soon as I enable `load_path_cache` one specific `require` in our codebase makes the execution crash with a `LoadError`:

```
LoadError: cannot load such file -- ../fastlane/lib/fastlane/version.rb
  /home/circleci/project/.bundle/ruby/2.3.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  Fastfile:491:in `block in parsing_binding'
  /home/circleci/project/fastlane/lib/fastlane/lane.rb:33:in `call'
  /home/circleci/project/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /home/circleci/project/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /home/circleci/project/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:72:in `block in parsing_binding'
  /home/circleci/project/fastlane/lib/fastlane/lane.rb:33:in `call'
  /home/circleci/project/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /home/circleci/project/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /home/circleci/project/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /home/circleci/project/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /home/circleci/project/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /home/circleci/project/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /home/circleci/project/.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /home/circleci/project/.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /home/circleci/project/.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /home/circleci/project/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /home/circleci/project/.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /home/circleci/project/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /home/circleci/project/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /home/circleci/project/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /home/circleci/project/bin/fastlane:38:in `<top (required)>'
  /home/circleci/project/.bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /home/circleci/project/.bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

This happens on Ubuntu, macOS and Windows alike:
https://circleci.com/gh/fastlane/fastlane/22611
https://circleci.com/gh/fastlane/fastlane/22612
https://ci.appveyor.com/project/KrauseFx/fastlane/build/1653

This is the `require` that is crashing bootsnap:
https://github.com/fastlane/fastlane/blob/2e28e6ff975df87096bbb802dfcc25d510473389/fastlane/Fastfile#L468-L472

The file in question is a super simple one:
https://github.com/fastlane/fastlane/blob/2e28e6ff975df87096bbb802dfcc25d510473389/fastlane/lib/fastlane/version.rb

If I remove the `require` and hardcode the return value of that "lane" (more or less a method) instead of returning `Fastlane::VERSION`, everything works as expected - and we get speed improvements of up to 65% 👍 

Any idea what could be going wrong here?

**Comment by janpio** [comment]
Turns out the `require` should actually be a `require_relative` which worked without `bootsnap`, but not with it installed. Fixing this also fixed the crash 💃 🕺 

See https://github.com/fastlane/fastlane/pull/13167 for our performance improvement numbers 💯
