### ISSUE TITLE
bootsnap error with heroku

### ISSUE THREAD

**Issue by AmrAdelKhalil** [Shopify/bootsnap#213]
Hello, I'm trying to deploy my app (rails api type) on heroku, while I'm deploying it it gives me that the deployment process has succeeded but it give me that error in logs

```
2018-12-03T20:06:36.393418+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': No such file to load -- pry.rb (LoadError)
2018-12-03T20:06:36.393443+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
2018-12-03T20:06:36.393445+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
2018-12-03T20:06:36.393446+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
2018-12-03T20:06:36.393448+00:00 app[web.1]: 	from /app/app/controllers/application_controller.rb:1:in `<main>'
2018-12-03T20:06:36.393450+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
2018-12-03T20:06:36.393459+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
2018-12-03T20:06:36.393461+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
2018-12-03T20:06:36.393462+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
2018-12-03T20:06:36.393464+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
2018-12-03T20:06:36.393465+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
2018-12-03T20:06:36.393467+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
2018-12-03T20:06:36.393469+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
2018-12-03T20:06:36.393470+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:374:in `block in require_or_load'
2018-12-03T20:06:36.393471+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
2018-12-03T20:06:36.393472+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
2018-12-03T20:06:36.393473+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
2018-12-03T20:06:36.393478+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
2018-12-03T20:06:36.393479+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
2018-12-03T20:06:36.393480+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:352:in `require_or_load'
2018-12-03T20:06:36.393481+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
2018-12-03T20:06:36.393482+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
2018-12-03T20:06:36.393483+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
2018-12-03T20:06:36.393484+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:330:in `depend_on'
2018-12-03T20:06:36.393485+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:84:in `block in depend_on'
2018-12-03T20:06:36.393487+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
2018-12-03T20:06:36.393488+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:84:in `rescue in depend_on'
2018-12-03T20:06:36.393489+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `depend_on'
2018-12-03T20:06:36.393490+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:244:in `require_dependency'
2018-12-03T20:06:36.393491+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
2018-12-03T20:06:36.393492+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:477:in `each'
2018-12-03T20:06:36.393494+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
2018-12-03T20:06:36.393495+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:475:in `each'
2018-12-03T20:06:36.393496+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:475:in `eager_load!'
2018-12-03T20:06:36.393498+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:356:in `eager_load!'
2018-12-03T20:06:36.393500+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application/finisher.rb:69:in `each'
2018-12-03T20:06:36.393501+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
2018-12-03T20:06:36.393502+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
2018-12-03T20:06:36.393503+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
2018-12-03T20:06:36.393504+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
2018-12-03T20:06:36.393505+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
2018-12-03T20:06:36.393506+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2018-12-03T20:06:36.393507+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
2018-12-03T20:06:36.393508+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
2018-12-03T20:06:36.393510+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
2018-12-03T20:06:36.393511+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
2018-12-03T20:06:36.393513+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
2018-12-03T20:06:36.393514+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
2018-12-03T20:06:36.393515+00:00 app[web.1]: 	from /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
2018-12-03T20:06:36.393516+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
2018-12-03T20:06:36.393518+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
2018-12-03T20:06:36.393520+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<main>'
2018-12-03T20:06:36.393522+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
2018-12-03T20:06:36.393523+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
2018-12-03T20:06:36.393525+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
2018-12-03T20:06:36.393528+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
2018-12-03T20:06:36.393530+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
2018-12-03T20:06:36.393532+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
2018-12-03T20:06:36.393534+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
2018-12-03T20:06:36.393539+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
2018-12-03T20:06:36.393542+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
2018-12-03T20:06:36.393543+00:00 app[web.1]: 	from config.ru:3:in `block in <main>'
2018-12-03T20:06:36.393545+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
2018-12-03T20:06:36.393546+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
2018-12-03T20:06:36.393549+00:00 app[web.1]: 	from config.ru:in `new'
2018-12-03T20:06:36.393550+00:00 app[web.1]: 	from config.ru:in `<main>'
2018-12-03T20:06:36.393552+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
2018-12-03T20:06:36.393554+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
2018-12-03T20:06:36.393557+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
2018-12-03T20:06:36.393560+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
2018-12-03T20:06:36.393561+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
2018-12-03T20:06:36.393563+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
2018-12-03T20:06:36.393566+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
2018-12-03T20:06:36.393568+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
2018-12-03T20:06:36.393570+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:53:in `start'
2018-12-03T20:06:36.393573+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
2018-12-03T20:06:36.393575+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
2018-12-03T20:06:36.393577+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
2018-12-03T20:06:36.393579+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
2018-12-03T20:06:36.393582+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
2018-12-03T20:06:36.393584+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
2018-12-03T20:06:36.393586+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
2018-12-03T20:06:36.393588+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
2018-12-03T20:06:36.393591+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
2018-12-03T20:06:36.393593+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
2018-12-03T20:06:36.393595+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
2018-12-03T20:06:36.393600+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
2018-12-03T20:06:36.393601+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
2018-12-03T20:06:36.393603+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
2018-12-03T20:06:36.393604+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
2018-12-03T20:06:36.393606+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
2018-12-03T20:06:36.393609+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
2018-12-03T20:06:36.393611+00:00 app[web.1]: 	from bin/rails:9:in `<main>'
2018-12-03T20:06:36.430752+00:00 app[web.1]: => Booting Puma
2018-12-03T20:06:36.430756+00:00 app[web.1]: => Rails 5.2.1 application starting in production 
2018-12-03T20:06:36.430757+00:00 app[web.1]: => Run `rails server -h` for more startup options
2018-12-03T20:06:36.430759+00:00 app[web.1]: Exiting
2018-12-03T20:06:36.505883+00:00 heroku[web.1]: Process exited with status 1
```

ruby version: 2.5.1
rails version: 5.2.1
bootsnap version: 1.3.2

**Comment by AmrAdelKhalil** [comment]
@rafaelfranca Hi, Yes it was as you said I've moved 'pry-rails' to production gems and everything is working now, I will close this as it is not related to this gem.
Sorry for disturbing you.
