### ISSUE TITLE
Failing tests on Linux

### ISSUE THREAD

**Issue by SamSaffron** [Shopify/bootsnap#22]
```
...........F............F................

Finished in 0.069678s, 588.4248 runs/s, 1420.8307 assertions/s.

  1) Failure:
Bootsnap::LoadPathCache::CacheTest#test_builtin_features [/home/sam/Source/bootsnap/test/load_path_cache/cache_test.rb:32]:
[Bootsnap::LoadPathCache::ReturnFalse] exception expected, not
Class: <Bootsnap::LoadPathCache::FallbackScan>
Message: <"Bootsnap::LoadPathCache::FallbackScan">
---Backtrace---
/home/sam/Source/bootsnap/lib/bootsnap/load_path_cache/cache.rb:83:in `block in find'
/home/sam/Source/bootsnap/lib/bootsnap/load_path_cache/cache.rb:53:in `synchronize'
/home/sam/Source/bootsnap/lib/bootsnap/load_path_cache/cache.rb:53:in `find'
/home/sam/Source/bootsnap/test/load_path_cache/cache_test.rb:32:in `block in test_builtin_features'
---------------


  2) Failure:
CompileCacheTest#test_no_write_permission [/home/sam/Source/bootsnap/test/compile_cache_test.rb:22]:
Expected /no write perm.*no write perm/m to match "".
```

After my PR these two specs are failing on Linux

**Comment by burke** [comment]
This fails on macOS sometimes too. I've been putting off hunting down the cause for a little while. It's probably something trivial.

**Comment by burke** [comment]
This was fixed recently.
