### ISSUE TITLE
'rails c' doesn't start 

### ISSUE THREAD

**Issue by joaopedromattos** [Shopify/bootsnap#223]
### What happens: 
When running 'rails c' on terminal it returns me this strange error I.
```
Running via Spring preloader in process 4371
Traceback (most recent call last):
	37: from -e:1:in `<main>'
	36: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	35: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	34: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	33: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	32: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
	31: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	30: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	29: from /home/joaopedromattos/Documentos/imob/imobiliario/bin/rails:9:in `<main>'
	28: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	27: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	26: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	25: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	24: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	23: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	22: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	21: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	20: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<main>'
	19: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/command.rb:44:in `invoke'
	18: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/command.rb:70:in `find_by_namespace'
	17: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/command/behavior.rb:79:in `lookup'
	16: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/command/behavior.rb:79:in `each'
	15: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/command/behavior.rb:80:in `block in lookup'
	14: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/command/behavior.rb:80:in `each'
	13: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/command/behavior.rb:84:in `block (2 levels) in lookup'
	12: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	11: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	10: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	 9: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 8: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 7: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 6: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 5: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 4: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/commands/console/console_command.rb:3:in `<main>'
	 3: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 2: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 1: from /home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/joaopedromattos/Documentos/imob/imobiliario/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- irb (LoadError)
```
Going to the pointed line in this file I find this method:

`raise Bootsnap::LoadPathCache::CoreExt.make_load_error(path)`

Does anybody knows what might be the problem? 

Thanks in advance!

**Comment by rafaelfranca** [comment]
`cannot load such file -- irb`

Are you able to load irb in your ruby?

**Comment by joaopedromattos** [comment]
Yes, I'm able to load irb.

**Comment by rafaelfranca** [comment]
Just for curiosity does it work when you create the app and install the gems inside a folder that has all lowercase character? It seems you app is inside `Documentos`.

**Comment by joaopedromattos** [comment]
Well, yes. I've always used rails and installed it's gems into projects that were inside Upper case characters folders, such as `Documentos`.

**Comment by rafaelfranca** [comment]
Right, I'm just asking to know if that is the cause of the issue. If it does working when the path is all lowercase it means our cache is not case sensitive and we need to fix this.

**Comment by jules2689** [comment]
What OS version is this? Mac OS is known to have a significant amount of issues with allowing mix-case files, and having case sensitivity issues - so it's possible this is the issue since making the cache `case sensitive` could affect different OSes.

**Comment by jules2689** [comment]
I found this, which may be related. https://github.com/bundler/bundler/issues/6929

**Comment by msdundar** [comment]
Same here. I'm getting:

`uninitialized constant Zeitwerk (NameError)`

**Comment by rafaelfranca** [comment]
This is not related and it is a bug in rails.

**Comment by molaeiali** [comment]
Having the same problem with @joaopedromattos
$ rails -v
rails 5.2.3
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
$ irb -v
irb 1.0.0 (2018-12-18)

**Comment by betoharres** [comment]
I had the same issue on Arch linux.
Saw the referenced post above saying to add `irb` to the Gemfile and decided to try it, and it worked!

Not sure why, too bad rails can't get up and running easily on a cross-platform environment ...

Gemfile:
```
group :development, :test do
  # Call 'byebug' anywhere in the code to stop
  # execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'irb', require: false
end
```

**Comment by apuppy** [comment]
> I had the same issue on Arch linux.
> Saw the referenced post above saying to add `irb` to the Gemfile and decided to try it, and it worked!
> 
> Not sure why, too bad rails can't get up and running easily on a cross-platform environment ...
> 
> Gemfile:
> 
> ```
> group :development, :test do
>   # Call 'byebug' anywhere in the code to stop
>   # execution and get a debugger console
>   gem 'byebug', platforms: %i[mri mingw x64_mingw]
>   gem 'irb', require: false
> end
> ```

It worked for me. Thanks.
