### ISSUE TITLE
rails/master doesn't boot with 1.4.0.pre3

### ISSUE THREAD

**Issue by fxn** [Shopify/bootsnap#233]
To reproduce, make sure you have the beta1 installed:

```
$ rails -v
Rails 6.0.0.beta1
```

generate an edge app

```
rails new foo --edge --skip-spring
```

and edit the `Gemfile` to depend on "~> 1.4.0.pre". Then,

```
bundle install
```

and finally

```
bin/rails runner 1
```

you'll see it errs. Same with the console or the server for example.

If you comment out the bootsnap setup line in `config/boot.rb`, the app boots.

**Comment by jules2689** [comment]
Can you please include the errors that you see?

**Comment by rafaelfranca** [comment]
```
Traceback (most recent call last):
	71: from bin/rails:4:in `<main>'
	70: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `require'
	69: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	68: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	67: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	66: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	65: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	64: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	63: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	62: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/commands.rb:18:in `<main>'
	61: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/command.rb:46:in `invoke'
	60: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/command/base.rb:65:in `perform'
	59: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	58: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	57: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	56: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/commands/runner/runner_command.rb:29:in `perform'
	55: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	54: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/command/actions.rb:22:in `require_application!'
	53: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `require'
	52: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	51: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	50: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	49: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	48: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	47: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	46: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	45: from /Users/rafaelfranca/src/foo/config/application.rb:3:in `<main>'
	44: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `require'
	43: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	42: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	41: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	40: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	39: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	38: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	37: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	36: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/all.rb:19:in `<main>'
	35: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/all.rb:19:in `each'
	34: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/all.rb:21:in `block in <main>'
	33: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `require'
	32: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	31: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	30: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	29: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	28: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	27: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	26: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	25: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:14:in `<main>'
	24: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:15:in `<module:Rails>'
	23: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:18:in `<class:Application>'
	22: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `require'
	21: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	20: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	19: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	18: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	17: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	16: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	15: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	14: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/application/cms/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	11: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	10: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 9: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 8: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	 7: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 6: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0.pre3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 5: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/railties/lib/rails/source_annotation_extractor.rb:8:in `<main>'
	 4: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	 3: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	 2: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/deprecation/proxy_wrappers.rb:125:in `initialize'
	 1: from /Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/deprecation/proxy_wrappers.rb:23:in `method_missing'
/Users/rafaelfranca/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-b2d8036df742/activesupport/lib/active_support/deprecation/proxy_wrappers.rb:148:in `warn': private method `warn' called for nil:NilClass (NoMethodError)
```

**Comment by rafaelfranca** [comment]
It looks like the `require` method here https://github.com/rails/rails/blob/master/activesupport/lib/active_support/deprecation/proxy_wrappers.rb#L125 is triggering a `method_missing`. I wonder what in bootsnap caused that method to trigger `method_missing`.

**Comment by rafaelfranca** [comment]
It is https://github.com/Shopify/bootsnap/commit/581bc3fa5967cecc6a77a36e2eb3f47793b14798.

Probably because the `module_function`-> `extend self` change.

I'll double check that.

**Comment by rafaelfranca** [comment]
Yup, that is the case. When we are using `extend(self)` the methods `require` and `load` became public and the `DeprecationProxy` will un-define it.

This was solved before in https://github.com/Shopify/bootsnap/pull/143.

`module_function` on the other hand make the method public in the class level but private in the instance level.

I'll change the code to use `module_function` and write a test to make sure we don't regress again.
