### ISSUE TITLE
Possible Bootsnap cache issue 

### ISSUE THREAD

**Issue by hraynaud** [Shopify/bootsnap#239]
Hi I suddenly encountered some weird behavior in my rails app that seems similar but not quite the same as others have reported in the past with bootsnap.  The issue is resolved for me but why it is makes no sense. I've documented what happened as best I can in this SO

https://stackoverflow.com/questions/54965760/rails-server-and-rails-console-crash-with-require-cannot-load-such-file-ra/54965861#54965861

If you guys find time to review and perhaps shed light on what happened that would be great. Otherwise i suppose you can feel free to close this. Thanks.

**Comment by hraynaud** [comment]
hi It looks like there is another issue all of a sudden.  I can run the application but I can't run any rake tasks.  Now I get this:

```
bundle exec rake db:migrate
rake aborted!
LoadError: cannot load such file -- minitest
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/test_unit/testing.rake:4:in `<main>'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `rescue in load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/test_unit/railtie.rb:26:in `block in <class:TestUnitRailtie>'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:246:in `instance_exec'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:246:in `block in run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:255:in `each'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:255:in `each_registered_block'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:246:in `run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:514:in `block in run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine/railties.rb:15:in `each'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine/railties.rb:15:in `each'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:514:in `run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:459:in `load_tasks'
/Users/herbyraynaud/code/personal/pwf-site/Rakefile:6:in `<top (required)>'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/herbyraynaud/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/Users/herbyraynaud/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'

Caused by:
Bootsnap::LoadPathCache::FallbackScan: Bootsnap::LoadPathCache::FallbackScan
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:81:in `block in find'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:50:in `synchronize'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/cache.rb:50:in `find'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/test_unit/railtie.rb:26:in `block in <class:TestUnitRailtie>'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:246:in `instance_exec'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:246:in `block in run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:255:in `each'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:255:in `each_registered_block'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/railtie.rb:246:in `run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:514:in `block in run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine/railties.rb:15:in `each'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine/railties.rb:15:in `each'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:514:in `run_tasks_blocks'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:459:in `load_tasks'
/Users/herbyraynaud/code/personal/pwf-site/Rakefile:6:in `<top (required)>'
/Users/herbyraynaud/code/personal/pwf-site/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/herbyraynaud/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/Users/herbyraynaud/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

**Comment by hraynaud** [comment]
I had to manually install mini-test gem at rake task now work.

**Comment by burke** [comment]
> What's weird is I wanted to verify that this was indeed the issue so I undid the change deleted the bootsnap cache in tmp/cache, deleted my vendor/bundle directory and re-performed bundle install and it's worked just fine. Even though that it had been broken for almost 2 days. It's as if temporarily moving bootsnap down below the other gems somehow got whatever was stuck unstuck. What's odd is that not even removing bootsnap from my application completely was able to get it working again but just temporarily moving it to near the bottom of the Gemfile did the trick?

This is really puzzling. I don't have any good theories for why this could be the case 🤔

**Comment by hraynaud** [comment]
@burke thanks for the reply. It's definitely a head scratcher and makes no sense whatsoever. I'm happy to close this issue just wanted to point it out because I've seen similar things reported and thought this might introduce additional areas of investigation. Clearly it's only raised more questions.  Thanks again.

**Comment by dogaoz** [comment]
This happened for us too. We had to remove the gem and re-install it to make it disappear.
Same symptoms.
App runs perfectly but all rake tasks fail.
