### ISSUE TITLE
Encoding::UndefinedConversionError when added Bootsnap (Rails 5.2.2 / Ruby 2.6.1).

### ISSUE THREAD

**Issue by bartekb** [Shopify/bootsnap#243]
Hi guys,

I have an issue when adding bootsnap into my app. My stack is based on Rails 5.2.2 / Ruby 2.6.1 / Ubuntu 16.04 / Puma 3.12.0 / Rubygems 3.0.3 / Bundler 1.17.3. I'm able to boot locally but when I open the app I get an Encoding::UndefinedConversionError. The app was upgraded from 4.2.11 to 5.1 and then 5.2.2. It works perfectly without bootsnap added. I've got the same error when deployed to Heroku (Ubuntu 18.04 stack). Below is a full framework traceback:

```
Encoding::UndefinedConversionError ("\xC3" from ASCII-8BIT to UTF-8):
  
activesupport (5.2.2) lib/active_support/core_ext/object/json.rb:38:in `encode'
activesupport (5.2.2) lib/active_support/core_ext/object/json.rb:38:in `to_json'
activesupport (5.2.2) lib/active_support/core_ext/object/json.rb:38:in `to_json'
activesupport (5.2.2) lib/active_support/json/encoding.rb:57:in `to_json'
json (2.2.0) lib/json/common.rb:224:in `generate'
json (2.2.0) lib/json/common.rb:224:in `generate'
activesupport (5.2.2) lib/active_support/json/encoding.rb:102:in `stringify'
activesupport (5.2.2) lib/active_support/json/encoding.rb:35:in `encode'
activesupport (5.2.2) lib/active_support/json/encoding.rb:22:in `encode'
activesupport (5.2.2) lib/active_support/core_ext/object/json.rb:41:in `to_json'
i18n-js (3.2.1) lib/i18n/js/formatters/base.rb:17:in `format_json'
i18n-js (3.2.1) lib/i18n/js/formatters/js.rb:10:in `block in format'
i18n-js (3.2.1) lib/i18n/js/formatters/js.rb:9:in `each'
i18n-js (3.2.1) lib/i18n/js/formatters/js.rb:9:in `format'
i18n-js (3.2.1) lib/i18n/js/segment.rb:51:in `write_file'
i18n-js (3.2.1) lib/i18n/js/segment.rb:38:in `save!'
i18n-js (3.2.1) lib/i18n/js.rb:45:in `each'
i18n-js (3.2.1) lib/i18n/js.rb:45:in `export'
i18n-js (3.2.1) lib/i18n/js/middleware.rb:78:in `verify_locale_files!'
i18n-js (3.2.1) lib/i18n/js/middleware.rb:13:in `call'
versionist (1.7.0) lib/versionist/middleware.rb:39:in `_call'
versionist (1.7.0) lib/versionist/middleware.rb:17:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.2) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
ahoy_matey (2.2.0) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```
I really appreciate any help you can provide.

**UPDATE:** it looks like the problem is in some YAML files with translations in the locales directory. Some files are parsed correctly but some of them cause an error:
```
"\xC3" from ASCII-8BIT to UTF-8
```
When I delete some of these files, the application starts without problems. This is odd because the files are parsed without errors by Rails when run without the Bootsnap enabled. Although there are valid UTF-8 files, there are probably some illegal characters in these files. However, I can not find these invalid characters.

As a workaround I disabled YAML caching by setting _compile_cache_yaml_ to FALSE. Now the application works with all YAML's and the Bootsnap enabled. However, it does not solve the main issue.

**Comment by burke** [comment]
I wonder, does it work if you blow away `tmp/cache`? If not, it would be helpful to see the file that breaks it, possibly a sanitized version if necessary or easy.
