### ISSUE TITLE
SystemStackError during Bundler.require

### ISSUE THREAD

**Issue by iain** [Shopify/bootsnap#246]
I'm sorry for opening an issue that is so scarce on the details, but it's hard to get much information.

I have a relatively simple Sinatra application, running on Alpine 3.9 with Ruby 2.5.3p105 (installed via apk). I run rake tasks on that application, and sometimes I get this error, but not always, so reproducing is tricky:

```
SystemStackError: stack level too deep
  from bootsnap/compile_cache/iseq.rb:12:in `to_binary'
  from bootsnap/compile_cache/iseq.rb:12:in `input_to_storage'
  from bootsnap/compile_cache/iseq.rb:37:in `fetch'
  from bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  from bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  from active_support/dependencies.rb:291:in `block in require'
  from active_support/dependencies.rb:257:in `load_dependency'
  from active_support/dependencies.rb:291:in `require'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
  from aws-sdk-ec2.rb:12:in `<main>'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  from bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  from bundler/runtime.rb:81:in `block (2 levels) in require'
  from bundler/runtime.rb:76:in `each'
  from bundler/runtime.rb:76:in `block in require'
  from bundler/runtime.rb:65:in `each'
  from bundler/runtime.rb:65:in `require'
  from bundler.rb:114:in `require'
  from config/application.rb:7:in `<main>'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  from bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  from active_support/dependencies.rb:291:in `block in require'
  from active_support/dependencies.rb:257:in `load_dependency'
  from active_support/dependencies.rb:291:in `require'
  from bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
  from Rakefile:21:in `block in <top (required)>'
  from rake/task.rb:273:in `block in execute'
  from rake/task.rb:273:in `each'
  from rake/task.rb:273:in `execute'
  from Rakefile:11:in `block (2 levels) in execute'
  from teachable_logger.rb:43:in `tagged'
  from Rakefile:10:in `block in execute'
  from raven/instance.rb:93:in `capture'
  from Rakefile:9:in `execute'
  from rake/task.rb:214:in `block in invoke_with_call_chain'
  from monitor.rb:226:in `mon_synchronize'
  from rake/task.rb:194:in `invoke_with_call_chain'
  from rake/task.rb:238:in `block in invoke_prerequisites'
  from rake/task.rb:236:in `each'
  from rake/task.rb:236:in `invoke_prerequisites'
  from rake/task.rb:213:in `block in invoke_with_call_chain'
  from monitor.rb:226:in `mon_synchronize'
  from rake/task.rb:194:in `invoke_with_call_chain'
  from rake/task.rb:248:in `block (2 levels) in invoke_prerequisites_concurrently'
  from rake/promise.rb:64:in `chore'
  from rake/promise.rb:34:in `block in value'
  from rake/promise.rb:32:in `synchronize'
  from rake/promise.rb:32:in `value'
  from rake/task.rb:252:in `reverse_each'
  from rake/task.rb:252:in `invoke_prerequisites_concurrently'
  from rake/multi_task.rb:11:in `invoke_prerequisites'
  from rake/task.rb:213:in `block in invoke_with_call_chain'
  from monitor.rb:226:in `mon_synchronize'
  from rake/task.rb:194:in `invoke_with_call_chain'
  from rake/task.rb:248:in `block (2 levels) in invoke_prerequisites_concurrently'
  from rake/promise.rb:64:in `chore'
  from rake/promise.rb:46:in `work'
  from rake/thread_pool.rb:104:in `process_queue_item'
  from rake/thread_pool.rb:124:in `block (2 levels) in start_thread'
```

This error is what is reported to Sentry. It stopped happening when I removed bootsnap, so that's why I conclude it's caused by bootsnap.

This is how I've configured bootsnap:

``` ruby
require "bootsnap"
Bootsnap.setup(
  cache_dir:            "tmp/cache",             # Path to your cache
  development_mode:     APP_ENV == :development, # Current working environment, e.g. RACK_ENV, RAILS_ENV, etc
  load_path_cache:      true,                    # Optimize the LOAD_PATH with a cache
  autoload_paths_cache: true,                    # Optimize ActiveSupport autoloads with cache
  disable_trace:        false,                   # (Alpha) Set `RubyVM::InstructionSequence.compile_option = { trace_instruction: false }`
  compile_cache_iseq:   true,                    # Compile Ruby code into ISeq cache, breaks coverage reporting.
  compile_cache_yaml:   true                     # Compile YAML into a cache
)
```

I was running bootsnap 1.4.1.

About the server, according to Sentry:

``` json
{"runtime":{"version":"ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-musl]","name":"ruby"},"os":{"kernel_version":"Linux 4d15dc5c2432 4.14.94-73.73.amzn1.x86_64 #1 SMP Tue Jan 22 20:25:24 UTC 2019 x86_64 Linux","version":"#1 SMP Tue Jan 22 20:25:24 UTC 2019","build":"4.14.94-73.73.amzn1.x86_64","name":"Linux"}}
```

I understand that this might not be enough information to go on. Let me know what other information you need.

**Comment by burke** [comment]
I'd be curious to see if this happens on ruby 2.6 as well: This error is in:

```ruby
        RubyVM::InstructionSequence.compile_file(path).to_binary
```

This is a ruby internal thing, which makes me suspicious that it's not something under bootsnap's control, which might behave better on a newer ruby.

**Comment by alextwoods** [comment]
The AWS SDK for ruby has run into this issue as well.  See: https://github.com/aws/aws-sdk-ruby/issues/2230

I don't believe this is a Bootsnap issue.  It looks like a ruby internal issue and at least in our case, was fixed in Ruby 2.7.0.

**Comment by jjb** [comment]
Happening with me under 2.7.0

**Comment by casperisfine** [comment]
Closing as unlikely to be a bootsnap issue. If someone were to provide a repo I wouldn't mind digging into this and eventually report it upstream, but as of no this issue isn't actionable.
