### ISSUE TITLE
bootsnap: `require': cannot load such file -- sass (LoadError)

### ISSUE THREAD

**Issue by Sophiecli** [Shopify/bootsnap#253]
Hello! This is my first time posting an issue as always seem to have managed to find the solution. However, not this time!

I have attempted to follow the solutions in regards to bootsnap, all listed in similar issues on this platform to no avail: 

Here is the current process that I have currently done: 
- updated in Gemfile: gem 'rails', '>= 5.2.2.1' due to security breach alerted by GitHub. 
- required to change in production.rb to: config.i18n.fallbacks = [I18n.default_locale], as current gem rails no longer includes the default locale.
- bundle installed. Bundle seem to be fine - no running errors.

ERROR HERE: 
Then when I pressed rails server to test the website, then these errors occur: 

```
/Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require': cannot load such file -- sass (LoadError)
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:80:in `register'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:36:in `rescue in require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:25:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/font-awesome-sass-5.0.13/lib/font-awesome-sass.rb:48:in `configure_sass'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/font-awesome-sass-5.0.13/lib/font-awesome-sass.rb:13:in `load!'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/font-awesome-sass-5.0.13/lib/font-awesome-sass.rb:78:in `<main>'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
	from /Users/sophieli/code/sophiecli/restaurants-api/config/application.rb:7:in `<main>'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/command/base.rb:65:in `perform'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/command.rb:46:in `invoke'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	from /Users/sophieli/code/sophiecli/restaurants-api/bin/rails:9:in `<top (required)>'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	from /Users/sophieli/.rbenv/versions/2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	from /Users/sophieli/code/sophiecli/restaurants-api/bin/spring:15:in `<top (required)>'
	from ./bin/rails:3:in `load'
	from ./bin/rails:3:in `<main>'
```

It seems to be a bootsnap issue and I have tried clearing the cache directory in the tmp folder, bundle install and specifically bundle installed bootsnap and I get these last two lines in which there is no solution suggested: 
Bundler attempted to update bootsnap but its version stayed the same
Bundle updated!

Hope this is more then enough information on the error logs I am receiving! 

Thank you in advance!

**Comment by burke** [comment]
Can you try with `1.4.2.rc3`? It likely won't fix but it could be that this error is misleading and masking the real error, which might point toward a solution. 1.4.2 fixes a thing that caused this behaviour sometimes.

**Comment by Sophiecli** [comment]
Thank you for this! I have tried your suggestion and still getting the exact same errors except with the updated version of Bootsnap...

**Comment by burke** [comment]
Try commenting out the `require 'bootsnap/setup'` line in `config/boot.rb` to see if you still get the error. If you do, it's just a misleading stacktrace.

**Comment by johnnybenson** [comment]
```
/opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/storext-3.0.0/lib/storext.rb (LoadError)
```

Experiencing a seemingly similar issue.

- Ruby 2.5.3
- Rails 5.2.3
- Bootsnap 1.4.2 (also tried 1.4.4)

Manually emptying `tmp/cache` had no effect

Commenting out `require 'bootsnap/setup'` line in `config/boot.rb` did resolve the issue.

The gem exists at the path, it seems like Bootsnap is not refreshing the cache

**Comment by bashford7** [comment]
Bit late to the party, was the error in not `bundle exec rails db:migrate` prior to running `rails server`?

**Comment by casperisfine** [comment]
Closing this as unlikely to be a bootsnap issue.
