### ISSUE TITLE
in linux use ruby-2.7.0 run rails appear TypeError

### ISSUE THREAD

**Issue by bcahlit** [Shopify/bootsnap#258]
when i use rvm install and use ruby-head  in linux( debian ) run rails s appear typeError

log is:
``` shell
➜  testapp2 git:(master) ✗ rvm use ruby-head --default
Using /home/bcahlit/.rvm/gems/ruby-head
➜  testapp2 git:(master) ✗ ruby -v                    
ruby 2.7.0dev (2019-05-10 trunk 79931dddba) [x86_64-linux]
➜  testapp2 git:(master) ✗ rails s    
Resolving dependencies...
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Warning: the lockfile is being updated to Bundler 2, after which you will be unable to return to Bundler 1.
Traceback (most recent call last):
	35: from bin/rails:3:in `<main>'
	34: from bin/rails:3:in `load'
	33: from /home/bcahlit/environment/testapp2/bin/spring:15:in `<top (required)>'
	32: from /home/bcahlit/environment/testapp2/bin/spring:15:in `require'
	31: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	30: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	29: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	28: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	27: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	26: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	25: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	24: from /home/bcahlit/environment/testapp2/bin/rails:8:in `<top (required)>'
	23: from /home/bcahlit/environment/testapp2/bin/rails:8:in `require_relative'
	22: from /home/bcahlit/environment/testapp2/config/boot.rb:4:in `<top (required)>'
	21: from /home/bcahlit/environment/testapp2/config/boot.rb:4:in `require'
	20: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/setup.rb:30:in `<top (required)>'
	19: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap.rb:30:in `setup'
	18: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache.rb:9:in `setup'
	17: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	16: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	15: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	14: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	13: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	12: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	11: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 9: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 8: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache/iseq.rb:1:in `<top (required)>'
	 7: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	 6: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	 5: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	 4: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 3: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': no implicit conversion of String into Integer (TypeError)
```

but when i use ruby-2.6.3 it no problem. i thint it because no adaptation

while in my mac ruby-2.7 is normal.  i don`t know is who problem.

**Comment by bcahlit** [comment]
when i use rvm install and use ruby-head  in linux( debian ) run rails s appear typeError

log is:
`➜  testapp2 git:(master) ✗ rvm use ruby-head --default
Using /home/bcahlit/.rvm/gems/ruby-head
➜  testapp2 git:(master) ✗ ruby -v                    
ruby 2.7.0dev (2019-05-10 trunk 79931dddba) [x86_64-linux]
➜  testapp2 git:(master) ✗ rails s    
Resolving dependencies...
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Warning: the lockfile is being updated to Bundler 2, after which you will be unable to return to Bundler 1.
Traceback (most recent call last):
	35: from bin/rails:3:in `<main>'
	34: from bin/rails:3:in `load'
	33: from /home/bcahlit/environment/testapp2/bin/spring:15:in `<top (required)>'
	32: from /home/bcahlit/environment/testapp2/bin/spring:15:in `require'
	31: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	30: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	29: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	28: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	27: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	26: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	25: from /home/bcahlit/.rvm/gems/ruby-head/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	24: from /home/bcahlit/environment/testapp2/bin/rails:8:in `<top (required)>'
	23: from /home/bcahlit/environment/testapp2/bin/rails:8:in `require_relative'
	22: from /home/bcahlit/environment/testapp2/config/boot.rb:4:in `<top (required)>'
	21: from /home/bcahlit/environment/testapp2/config/boot.rb:4:in `require'
	20: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/setup.rb:30:in `<top (required)>'
	19: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap.rb:30:in `setup'
	18: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache.rb:9:in `setup'
	17: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	16: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	15: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	14: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	13: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	12: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	11: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 9: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 8: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache/iseq.rb:1:in `<top (required)>'
	 7: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	 6: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	 5: from /home/bcahlit/.rvm/gems/ruby-head/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	 4: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 3: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/bcahlit/.rvm/gems/ruby-head/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': no implicit conversion of String into Integer (TypeError)
`

but when i use ruby-2.6.3 it no problem. i thint it because no adaptation

while in my mac ruby-2.7 is normal.  i don`t know is who problem.

**Comment by burke** [comment]
Looking at the code, it kind of seems like this is a failure in ruby, not bootsnap. I don't have time to debug it this week, but I'd guess this is just a transient failure from building off of master/trunk.

**Comment by jasnow** [comment]
FYI: Got this error today (with "rails s") with the new Ruby 2.7.0-preview1 version on Mac 10.12.6.
```
/Users/USER/.rvm/gems/ruby-2.7.0-preview1@ruby2.7-rails5.2/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': no implicit conversion of String into Integer (TypeError)
```

**Comment by leather-s** [comment]
@jasnow Im also getting this same error on 2.7.0-preview1 on mac 10.14.5

**Comment by kingdonb** [comment]
I had other problems with Rails Edge (6.1.0alpha) which I just tried to install, (not this problem, not Rails problems but other gem problems which are not related to bootsnap)  I am building a new Rails app as we speak, trying to settle on what versions.  I should mention using 2.7.0-preview1 on Mac

So I backed down to Rails 5.2.3, latest stable.  Rails new, again on 2.7.0-preview1 and I find this error from bootsnap.

For what it's worth, the issue seems to be fixed upstream in Rails alphas.

It might be better to use Rails alpha and Ruby preview together, is all I'm saying, since I didn't have this problem.  I will back off to the stable Ruby version and probably see this issue resolved right away.  My suggestion is to use a stable Ruby version with your stable Rails 5.2 app.

**Comment by beatmadsen** [comment]
Replicated on MacOS Mojave with rbenv, ruby 2.7.0-preview1, rails 6.0.0.rc2

**Comment by jcserracampos** [comment]
I am facing the same error with macOS Mojave, ruby 2.7.0-preview and rails 6.0.0.rc2.

My log:

```
* bin/rails: Spring inserted
       rails  webpacker:install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Traceback (most recent call last):
	36: from bin/rails:3:in `<main>'
	35: from bin/rails:3:in `load'
	34: from /Users/juliocampos/Projects/Personal/voiceless/bin/spring:15:in `<top (required)>'
	33: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	32: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	31: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	30: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	29: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	28: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	27: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	26: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	25: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	24: from /Users/juliocampos/Projects/Personal/voiceless/bin/rails:8:in `<top (required)>'
	23: from /Users/juliocampos/Projects/Personal/voiceless/bin/rails:8:in `require_relative'
	22: from /Users/juliocampos/Projects/Personal/voiceless/config/boot.rb:4:in `<top (required)>'
	21: from /Users/juliocampos/Projects/Personal/voiceless/config/boot.rb:4:in `require'
	20: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/setup.rb:30:in `<top (required)>'
	19: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap.rb:30:in `setup'
	18: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache.rb:9:in `setup'
	17: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	16: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
	15: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	14: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `block in require'
	13: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	12: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	11: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 9: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 8: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache/iseq.rb:1:in `<top (required)>'
	 7: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
	 6: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	 5: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `block in require'
	 4: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 3: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': no implicit conversion of String into Integer (TypeError)
       rails  webpacker:install:react
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Traceback (most recent call last):
	36: from bin/rails:3:in `<main>'
	35: from bin/rails:3:in `load'
	34: from /Users/juliocampos/Projects/Personal/voiceless/bin/spring:15:in `<top (required)>'
	33: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	32: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	31: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	30: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	29: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	28: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	27: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	26: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	25: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	24: from /Users/juliocampos/Projects/Personal/voiceless/bin/rails:8:in `<top (required)>'
	23: from /Users/juliocampos/Projects/Personal/voiceless/bin/rails:8:in `require_relative'
	22: from /Users/juliocampos/Projects/Personal/voiceless/config/boot.rb:4:in `<top (required)>'
	21: from /Users/juliocampos/Projects/Personal/voiceless/config/boot.rb:4:in `require'
	20: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/setup.rb:30:in `<top (required)>'
	19: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap.rb:30:in `setup'
	18: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache.rb:9:in `setup'
	17: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	16: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
	15: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	14: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `block in require'
	13: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	12: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	11: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 9: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 8: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache/iseq.rb:1:in `<top (required)>'
	 7: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
	 6: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	 5: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `block in require'
	 4: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 3: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/juliocampos/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': no implicit conversion of String into Integer (TypeError)
```

**Comment by kgrz** [comment]
Ran into the same issue and noticed that this happens in the C extension. Also, it looks like `master` branch has the [fix](https://github.com/Shopify/bootsnap/commit/a163c7cddfccd68277f6ea43b1831378509817c9).

<img width="1226" alt="Screenshot 2019-08-06 at 9 11 41 PM" src="https://user-images.githubusercontent.com/400299/62554561-f235f500-b88e-11e9-95bb-a034136ec52e.png">

**Comment by jcserracampos** [comment]
@kou Do your commit fix this?

**Comment by jcserracampos** [comment]
@bcahlit Can we reopen this issue?

**Comment by kgrz** [comment]
Checked against master and it fixes the issue for me. Ruby 2.7 preview1 and rails 6 rc

**Comment by Leo328** [comment]
```
/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': no implicit con
version of String into Integer (TypeError)
```

Running into the sale issue trying to start up a Rails App on Ubuntu 18.04 on WSL2.

I have the latest commit mentioned above and cannot proceed.

**Comment by ffloyd** [comment]
Have same problems with preview2
