### ISSUE TITLE
Bootsnap::LoadPathCache::FallbackScan - cannot load such file — bindex

### ISSUE THREAD

**Issue by Zeesui** [Shopify/bootsnap#268]
Create a new app,when I run rails s, it throws me a cannot load such file -- bindex error.
 I tried gem install bindex, it throws me the same error,
 tried bundle update - the same error, 
tried gem update - the same error.
 I have no idea how to fix this.
Please help me out.

macos mojave 10.14.5
rails 6.0.o.rc1
ruby 2.6.1

```
 ⮀ ⭠ master± ⮀ rails s
=> Booting Puma
=> Rails 6.0.0.rc1 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
    77: from bin/rails:3:in `<main>'
    76: from bin/rails:3:in `load'
    75: from /Users/sujize/app_7/bin/spring:15:in `<top (required)>'
    74: from /Users/sujize/app_7/bin/spring:15:in `require'
    73: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
    72: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
    71: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
    70: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
    69: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
    68: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
    67: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
    66: from /Users/sujize/app_7/bin/rails:9:in `<top (required)>'
    65: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
    64: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
    63: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
    62: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    61: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
    60: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    59: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
    58: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
    57: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<main>'
    56: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/command.rb:46:in `invoke'
    55: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/command/base.rb:65:in `perform'
    54: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    53: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    52: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    51: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:138:in `perform'
    50: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:138:in `tap'
    49: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
    48: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:37:in `start'
    47: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
    46: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
    45: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
    44: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
    43: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
    42: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
    41: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
    40: from config.ru:in `<main>'
    39: from config.ru:in `new'
    38: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
    37: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
    36: from config.ru:3:in `block in <main>'
    35: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
    34: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
    33: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
    32: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
    31: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/zeitwerk-2.1.8/lib/zeitwerk/kernel.rb:23:in `require'
    30: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    29: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
    28: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    27: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
    26: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
    25: from /Users/sujize/app_7/config/environment.rb:5:in `<main>'
    24: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/application.rb:362:in `initialize!'
    23: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:60:in `run_initializers'
    22: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
    21: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
    20: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
    19: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `call'
    18: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each'
    17: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
    16: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
    15: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    14: from /Users/sujize/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
    13: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
    12: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `run'
    11: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `instance_exec'
    10: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/web-console-4.0.0/lib/web_console/railtie.rb:11:in `block in <class:Railtie>'
     9: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
     8: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
     7: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
     6: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/zeitwerk-2.1.8/lib/zeitwerk/kernel.rb:23:in `require'
     5: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26:in `require'
     4: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:40:in `rescue in require'
     3: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
     2: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
     1: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': **cannot load such file -- bindex (LoadError)**
```
The error:
```
1: from /Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/sujize/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': **cannot load such file -- bindex (LoadError)**
```

Github:https://github.com/Zeesui/app_7

**Comment by rafaelfranca** [comment]
If you remove the line with `bootsnap/setup` from your boot.rb does the issue still happen?

**Comment by bellom** [comment]
same issue after removing `bootsnap/setup`

**Comment by rgaufman** [comment]
Any ideas? same issue here

**Comment by bellom** [comment]
# solution::::::
> goto config/initializers/boot.rb
> remove or comment out require 'bootsnap/setup'

I hope it works for you,

**Comment by bellom** [comment]
If above solution didn't work for you, kindly try and install with rbenv, solution below;

_Here is what I did_ :point_down: 
```
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL
sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev readline-doc libssl-doc
rbenv install 2.5.1
rbenv global 2.5.1
gem install bundler
rbenv rehash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
gem install rails -v 5.2.0
rbenv rehash
```

**Comment by Zeesui** [comment]
A friend of mine cloned the project and it worked well on her computer，I think maybe the problem is my local machine,and considering that both my native rails and ruby are the latest versions.Is it possible that the version is incompatible？So I tried to degrade rails and ruby, and the problem was solved.Here is my solution:run: gem install rails -v 5.6.2 ,and run: rvm install 2.5.3

**Comment by casperisfine** [comment]
Closing this as unlikely to be a bootstrap issue.
