### ISSUE TITLE
Heroku Bootsnap error

### ISSUE THREAD

**Issue by danagri** [Shopify/bootsnap#284]
Hello. 
I'm trying to deploy my app on heroku, the deployment process has succeeded, but it give me this error in logs. I'm new to ruby, rails and heroku too, so i don't know what to do.
Ruby - 2.6.3
Rails - 6.0.1
Bootsnap - 1.4.2
```
2019-12-08T18:42:48.636861+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
2019-12-08T18:42:48.636863+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2019-12-08T18:42:48.636865+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
2019-12-08T18:42:48.636868+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2019-12-08T18:42:48.636870+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
2019-12-08T18:42:48.636872+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency
2019-12-08T18:42:48.636876+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
2019-12-08T18:42:48.636878+00:00 app[web.1]: 	from bin/rails:4:in `<main>'
2019-12-08T18:42:48.733346+00:00 heroku[web.1]: State changed from starting to crashed
2019-12-08T18:42:48.716076+00:00 heroku[web.1]: Process exited with status 1

```

**Comment by danagri** [comment]
The problem is resolved.

**Comment by DJA89** [comment]
How?

**Comment by iLucker93** [comment]
How?
