### ISSUE TITLE
Operation not supported 

### ISSUE THREAD

**Issue by joostliketoast** [Shopify/bootsnap#29]
I just tried adding bootsnap to my rails project but when i try to load the rails server i run into the following problem:
`.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/iseq.rb:30:in fetch': Operation not supported (Errno::EOPNOTSUPP)`

full stack trace:

```
/home/joost/.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch': Operation not supported (Errno::EOPNOTSUPP)
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/iseq.rb:30:in `load_iseq'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/yaml.rb:34:in `install!'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache.rb:12:in `setup'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/bootsnap-0.2.12/lib/bootsnap.rb:29:in `setup'
        from /mnt/c/Workspace/kennislink/config/boot.rb:6:in `<top (required)>'
        from /mnt/c/Workspace/kennislink/bin/rails:8:in `require_relative'
        from /mnt/c/Workspace/kennislink/bin/rails:8:in `<top (required)>'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
        from /home/joost/.rvm/gems/ruby-2.4.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
        from /home/joost/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/joost/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /mnt/c/Workspace/kennislink/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

**Comment by SamSaffron** [comment]
likely cause you are on Linux and Linux support for extended filesystem attribs is sketchy at best, disable iseq and yaml caches for now.

**Comment by burke** [comment]
Should be fixed by https://github.com/Shopify/bootsnap/pull/43

**Comment by burke** [comment]
curious to know if 0.3.0.pre works for you.

**Comment by burke** [comment]
0.3.0 released, with full linux support.
