### ISSUE TITLE
Obscure failure when Rails config files can't be found

### ISSUE THREAD

**Issue by pirj** [Shopify/bootsnap#290]
When running `rspec` for an application for which a new `config/something.yml.example` file has been added, and some code expects that `config/something.yml` is present, an obscure error appears:

```
         13: from /Users/pirj/.rvm/gems/ruby-2.5.1@my_project/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
         12: from /Users/pirj/source/my_project/lib/models/some_model.rb:35:in `<top (required)>'
         11: from /Users/pirj/source/my_project/lib/models/some_model.rb:50:in `<class:SomeModel>'
         10: from /Users/pirj/source/my_project/lib/concerns/some_concern.rb:68:in `some_attribute'
          9: from /Users/pirj/source/my_project/lib/concerns/some_concern.rb:68:in `delete'
          8: from /Users/pirj/source/my_project/lib/concerns/some_concern.rb:68:in `block in some_attribute'
          1: from /Users/pirj/.rvm/gems/ruby-2.5.1@my_project/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/yaml.rb:50:in `block in install!'
/Users/pirj/.rvm/gems/ruby-2.5.1@my_project/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/yaml.rb:50:in `fetch': No such file or directory - bs_fetch:open_current_file:open (Errno::ENOENT)
```
(scrubbed)

where the line that is fetching conf is:
```ruby
      @config = YAML.load_file(Rails.root.join(path)).deep_symbolize_keys[env]
```

WDYT of adding handling for this case to `lib/bootsnap/compile_cache/yaml.rb`:
```diff
          rescue Errno::EACCES
            Bootsnap::CompileCache.permission_error(path)
+           rescue => Errno::ENOENT
+             # Something explaining which file can't be found
          end
        end
```

I can send a pull request real quick but would appreciate if you suggest what should be raised and how since I'm not very familiar with the internals of Bootsnap.

**Comment by burke** [comment]
Yes, that seems completely fine!
