### ISSUE TITLE
Currently requires app/assets/config/manifest.js, but I want to get rid of app/assets given that I'm using webpacker

### ISSUE THREAD

**Issue by adamzerner** [Shopify/bootsnap#291]
I'm using bootsnap 1.4.5 in my Rails app. I'm using webpacker for everything now — JS, CSS and images — so I would like to get rid of `app/assets` given that it isn't being used anymore. However, when I do, bootsnap gives me an error saying that it needs `app/assets/config/manifest.js` (see below). My question is if there's anything I can do to remove this dependency.

```
code/scout-db [master] » rails s
=> Booting Puma
=> Rails 6.0.1 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	68: from bin/rails:3:in `<main>'
	67: from bin/rails:3:in `load'
	66: from /Users/adamzerner/code/scout-db/bin/spring:15:in `<top (required)>'
	65: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	64: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	63: from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	62: from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	61: from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	60: from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	59: from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	58: from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	57: from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	56: from /Users/adamzerner/code/scout-db/bin/rails:9:in `<top (required)>'
	55: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
	54: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	53: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
	52: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	51: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	50: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	49: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	48: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	47: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
	46: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/command.rb:46:in `invoke'
	45: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/command/base.rb:65:in `perform'
	44: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	43: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	42: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	41: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	40: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	39: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	38: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:37:in `start'
	37: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	36: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/server.rb:354:in `wrapped_app'
	35: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/server.rb:219:in `app'
	34: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	33: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/builder.rb:40:in `parse_file'
	32: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/builder.rb:49:in `new_from_string'
	31: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/builder.rb:49:in `eval'
	30: from config.ru:in `<main>'
	29: from config.ru:in `new'
	28: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `initialize'
	27: from /Library/Ruby/Gems/2.6.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `instance_eval'
	26: from config.ru:3:in `block in <main>'
	25: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	24: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
	23: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	22: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
	21: from /Library/Ruby/Gems/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	20: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	19: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	18: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	17: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	16: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	15: from /Users/adamzerner/code/scout-db/config/environment.rb:5:in `<main>'
	14: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/application.rb:363:in `initialize!'
	13: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:60:in `run_initializers'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:347:in `each'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	 3: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	 2: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `run'
	 1: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `instance_exec'
/Library/Ruby/Gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
code/scout-db [master] »
```

**Comment by rafaelfranca** [comment]
Thank you for the issue but this is not related to bootsnap. If you want to remove sprockets-rails as a dependency of your project, and with that this error, you need to not load the `sprockets/railtie` on your `config/application.rb`.

Look for `require 'sprockets/railtie'` or `require 'rails/all'` in that file.
