### ISSUE TITLE
Bootsnap compatibility rails 2.3.18/ruby 2.3.1

### ISSUE THREAD

**Issue by daviceitor** [Shopify/bootsnap#292]
Hi,
I'm trying to use bootsnap on an old rails 2.3.18 app but i'm getting the error:
```
NoMethodError: undefined method 'mattr_accessor' for ActiveSupport::Dependencies:Module
Did you mean?  attr_accessor
  /app/vendor/cache/rails-c2be41e8dba7/activesupport/lib/active_support/dependencies.rb:8:in '<module:Dependencies>'
  /app/vendor/cache/rails-c2be41e8dba7/activesupport/lib/active_support/dependencies.rb:4:in '<module:ActiveSupport>'
  /app/vendor/cache/rails-c2be41e8dba7/activesupport/lib/active_support/dependencies.rb:3:in '<top (required)>'
  /bundle/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in 'require'
  /bundle/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in 'require'
  /bundle/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache.rb:35:in 'setup'
  /bundle/gems/bootsnap-1.1.1/lib/bootsnap.rb:23:in 'setup'
```
There is any chance that i can use it in this stack? any help or idea will be really appreciated

**Comment by rafaelfranca** [comment]
I'm sorry but bootsnap don't support Rails 2.3
