### ISSUE TITLE
Error loading ISeq from cache for sass-3.4.23

### ISSUE THREAD

**Issue by joshRpowell** [Shopify/bootsnap#30]
Hi @burke! Thanks for this project.  On my first try, it yelled back at me. 

The 'fix' got me to the next gem with a similar issue.  Please let me know if this is too much info. 
I'll submit a separate issue for each gem I run into a similar issue with. 

Details below:

```
16:03:11 web.1    | [90160] Puma starting in cluster mode...
16:03:11 web.1    | [90160] * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
16:03:11 web.1    | [90160] * Min threads: 5, max threads: 5
16:03:11 web.1    | [90160] * Environment: development
16:03:11 web.1    | [90160] * Process workers: 2
16:03:11 web.1    | [90160] * Preloading application
16:03:12 web.1    | Error loading ISeq from cache for /Users/jpowell/.rvm/gems/ruby-2.4.1@milner/gems/sass-3.4.23/lib/sass/script/functions.rb!
16:03:12 web.1    | You can likely fix this by running:
16:03:12 web.1    |   xattr -c /Users/jpowell/.rvm/gems/ruby-2.4.1@milner/gems/sass-3.4.23/lib/sass/script/functions.rb
16:03:12 web.1    | ...but, first, please make sure @burke knows you ran into this bug!
16:03:12 web.1    | He will want to see the results of:
16:03:12 web.1    |   /bin/ls -l@ /Users/jpowell/.rvm/gems/ruby-2.4.1@milner/gems/sass-3.4.23/lib/sass/script/functions.rb
16:03:12 web.1    | and:
16:03:12 web.1    |   xattr -p user.aotcc.key /Users/jpowell/.rvm/gems/ruby-2.4.1@milner/gems/sass-3.4.23/lib/sass/script/functions.rb
16:03:12 web.1    | [90160] ! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'bootstrap-sass'.
16:03:12 web.1    | Gem Load Error is: Result too large
```

results from:
```
/bin/ls -l@ /Users/jpowell/.rvm/gems/ruby-2.4.1@milner/gems/sass-3.4.23/lib/sass/script/functions.rb
```
=
```
-rw-r--r--@ 1 jpowell  staff  107122 May  3 19:46 /Users/jpowell/.rvm/gems/ruby-2.4.1@milner/gems/sass-3.4.23/lib/sass/script/functions.rb
	user.aotcc.key	    22
	user.aotcc.value	167991
```

results from:
```
 xattr -p user.aotcc.key /Users/jpowell/.rvm/gems/ruby-2.4.1@milner/gems/sass-3.4.23/lib/sass/script/functions.rb
```
=
```
0B 0C D2 F2 E4 3C 2F 90 02 00 C5 E2 00 00 E3 6B
0A 59 00 00 00 00
```

here's the full trace: 
```
16:03:12 web.1    | Backtrace for gem load error is:
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/iseq.rb:30:in `load_iseq'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/script.rb:34:in `<module:Script>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/script.rb:8:in `<module:Sass>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/script.rb:3:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/engine.rb:46:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass.rb:99:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass.rb:60:in `configure_sass'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass.rb:16:in `load!'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass.rb:94:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
16:03:12 web.1    | /Users/jpowell/Dropbox/Clients/crm/config/application.rb:20:in `<top (required)>'
16:03:12 web.1    | /Users/jpowell/Dropbox/Clients/crm/config/environment.rb:2:in `require'
16:03:12 web.1    | /Users/jpowell/Dropbox/Clients/crm/config/environment.rb:2:in `<top (required)>'
16:03:12 web.1    | config.ru:3:in `require'
16:03:12 web.1    | config.ru:3:in `block in <main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:55:in `instance_eval'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:55:in `initialize'
16:03:12 web.1    | config.ru:in `new'
16:03:12 web.1    | config.ru:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:49:in `eval'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:49:in `new_from_string'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:40:in `parse_file'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/cluster.rb:391:in `run'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/puma:22:in `load'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/puma:22:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
16:03:12 web.1    | Bundler Error Backtrace:
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bootstrap-sass'. (Bundler::GemRequireError)
16:03:12 web.1    | Gem Load Error is: Result too large
16:03:12 web.1    | Backtrace for gem load error is:
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/compile_cache/iseq.rb:30:in `load_iseq'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/script.rb:34:in `<module:Script>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/script.rb:8:in `<module:Sass>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/script.rb:3:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass/engine.rb:46:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/sass-3.4.23/lib/sass.rb:99:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass.rb:60:in `configure_sass'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass.rb:16:in `load!'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass.rb:94:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.2.12/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
16:03:12 web.1    | /Users/jpowell/Dropbox/Clients/crm/config/application.rb:20:in `<top (required)>'
16:03:12 web.1    | /Users/jpowell/Dropbox/Clients/crm/config/environment.rb:2:in `require'
16:03:12 web.1    | /Users/jpowell/Dropbox/Clients/crm/config/environment.rb:2:in `<top (required)>'
16:03:12 web.1    | config.ru:3:in `require'
16:03:12 web.1    | config.ru:3:in `block in <main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:55:in `instance_eval'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:55:in `initialize'
16:03:12 web.1    | config.ru:in `new'
16:03:12 web.1    | config.ru:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:49:in `eval'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:49:in `new_from_string'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:40:in `parse_file'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/cluster.rb:391:in `run'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/puma:22:in `load'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/puma:22:in `<main>'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
16:03:12 web.1    | /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
16:03:12 web.1    | Bundler Error Backtrace:
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
16:03:12 web.1    | 	from /Users/jpowell/Dropbox/Clients/crm/config/application.rb:20:in `<top (required)>'
16:03:12 web.1    | 	from /Users/jpowell/Dropbox/Clients/crm/config/environment.rb:2:in `require'
16:03:12 web.1    | 	from /Users/jpowell/Dropbox/Clients/crm/config/environment.rb:2:in `<top (required)>'
16:03:12 web.1    | 	from config.ru:3:in `require'
16:03:12 web.1    | 	from config.ru:3:in `block in <main>'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:55:in `instance_eval'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:55:in `initialize'
16:03:12 web.1    | 	from config.ru:in `new'
16:03:12 web.1    | 	from config.ru:in `<main>'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:49:in `eval'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:49:in `new_from_string'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/rack-2.0.2/lib/rack/builder.rb:40:in `parse_file'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/cluster.rb:391:in `run'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/puma:22:in `load'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/puma:22:in `<main>'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
16:03:12 web.1    | 	from /Users/jpowell/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
16:03:13 web.1    | exited with code 1
16:03:13 system   | sending SIGTERM to all processes
```

**Comment by burke** [comment]
It's odd that this would happen on the first run. I've seen this occasionally internally at Shopify and never been able to track down exactly how it's able to desync the key and value like this. I don't have a solution off the top of my head. I'll try to debug it more thoroughly next time someone in the same building as me has this problem.

**Comment by joshRpowell** [comment]
🤙

[Joshua Powell - Contact Using Hop](http://GetHop.com/?_hmid=1494518998)

On May 11, 2017 at 15:47 GMT, Burke Libbey <notifications@github.com> wrote:

It's odd that this would happen on the first run. I've seen this occasionally internally at Shopify and never been able to track down exactly how it's able to desync the key and value like this. I don't have a solution off the top of my head. I'll try to debug it more thoroughly next time someone in the same building as me has this problem.

**Comment by burke** [comment]
Cache implementation is completely changed now, so I don't expect this to recur with 0.3.0+
