### ISSUE TITLE
Cannot load such file -- rexml/document (LoadError) : Ruby 3

### ISSUE THREAD

**Issue by poudelprakash** [Shopify/bootsnap#325]
I updated my rails project to use ruby 3 and encountered this issue:

```
/Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- rexml/document (LoadError)
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activemerchant-1.114.0/lib/active_merchant.rb:37:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/bundler/gems/spree-bc02c8ade3b6/core/lib/spree/core.rb:2:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/bundler/gems/spree-bc02c8ade3b6/core/lib/spree_core.rb:2:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/bundler/gems/spree-bc02c8ade3b6/lib/spree.rb:1:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /Users/prakash/workspaces/2020/ecom/ecom_api/config/application.rb:20:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/workspaces/2020/ecom/ecom_api/bin/rails:9:in `<top (required)>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/prakash/workspaces/2020/ecom/ecom_api/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
ecom_api - ruby-3! ❯ rails c
/Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- rexml/document (LoadError)
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activemerchant-1.114.0/lib/active_merchant.rb:37:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/bundler/gems/spree-bc02c8ade3b6/core/lib/spree/core.rb:2:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/bundler/gems/spree-bc02c8ade3b6/core/lib/spree_core.rb:2:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/bundler/gems/spree-bc02c8ade3b6/lib/spree.rb:1:in `<main>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /Users/prakash/workspaces/2020/ecom/ecom_api/config/application.rb:20:in `<top (required)>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from -e:1:in `<main>'
```

**Comment by geeknees** [comment]
Hello.
I think the cause is that you are using REXML somewhere in your application and REXML is no longer built-in.

> The following default gems are now bundled gems.
>    rexml

Adding the following to your Gemfile may solve the problem.

https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

```
gem 'rexml'
```

**Comment by poudelprakash** [comment]
@geeknees You are right, Adding rexml solved the issue.
But bundled gems are supposed to be automatically installed with ruby install right?

**Comment by geeknees** [comment]
Indeed...

The Japanese release text had supplementary information.

> 以下のライブラリが新たに bundled gems になりました。Bundler から利用する場合は Gemfile に明示的に指定してください。 

This means... The following libraries are now bundled gems, and `must be explicitly specified in your Gemfile if you want to use them from Bundler` .  I'm guessing it's an error when running bundle exec rspec etc.

I don't know if this is a problem that should be solved by bootsnap or not, so I'd like to ask the maintainers to make a decision.

**Comment by poudelprakash** [comment]
@rafaelfranca , @casperisfine

**Comment by x-yuri** [comment]
> I think the cause is that you are using REXML somewhere in your application

Sort of. Take a look at the stack trace:

```
/Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- rexml/document (LoadError)
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/prakash/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activemerchant-1.114.0/lib/active_merchant.rb:37:in `<main>'
        ...
```

https://github.com/activemerchant/active_merchant/blob/v1.117.0/lib/active_merchant.rb#L37

In my case it was `selenium-webdriver`:

https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-7/rb/lib/selenium/webdriver/firefox.rb#L22

Ideally the changes are to be made in the corresponding gems. And this issue can probably be closed.

**Comment by casperisfine** [comment]
Yes, this as nothing to do with bootsnap. It's a ruby 3 change, you can reproduce it with bootsnap removed.

**Comment by yshmarov** [comment]
Also had this error problem when creating a new Rails 6/7, Ruby 3 app and running `bin/rails test`.
Fix:
```
gem install rexml
bin/rails db:drop db:create db:migrate RAILS_ENV=test
bin/rails test
```
