### ISSUE TITLE
Failing with "No space left on device (Errno::ENOSP)"?

### ISSUE THREAD

**Issue by zmoazeni** [Shopify/bootsnap#33]
Hey there, I just tried it out on our codebase and got this. Ubuntu 16.04

```
/home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch': No space left on device (Errno::ENOSPC)
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/compile_cache/iseq.rb:30:in `load_iseq'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/2.3.0/yaml.rb:6:in `<main>'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/compile_cache/yaml.rb:34:in `install!'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap/compile_cache.rb:12:in `setup'
	from /home/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-0.2.14/lib/bootsnap.rb:29:in `setup'
```

But I have plenty of space available. Any idea what this could be failing on? I'm just using the typical setup from https://github.com/Shopify/bootsnap/blob/d47839c9f10e5e0462809973dfaceb53164039f1/README.md#usage

**Comment by burke** [comment]
likely related to https://github.com/Shopify/bootsnap/issues/20

We don't use the iseq cache on linux, so it's definitely going to be at best a little unstable.

**Comment by zmoazeni** [comment]
Ah thanks. I did skim that but wasn't sure if it was related.

**Comment by burke** [comment]
This will be addressed by https://github.com/Shopify/bootsnap/pull/43
