### ISSUE TITLE
after i run project error comes what should i do plz help me

### ISSUE THREAD

**Issue by kajal-ndinfo** [Shopify/bootsnap#335]
```
Traceback (most recent call last):
        101: from bin/rails:3:in `<main>'
        100: from bin/rails:3:in `load'
         99: from /home/ndinfo/property/bin/spring:15:in `<top (required)>'
         98: from /home/ndinfo/property/bin/spring:15:in `require'
         97: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
         96: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
         95: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
         94: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
         93: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
         92: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
         91: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
         90: from /home/ndinfo/property/bin/rails:9:in `<top (required)>'
         89: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
         88: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
         87: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
         86: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         85: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         84: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         83: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         82: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         81: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
         80: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
         79: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
         78: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
         77: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         76: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         75: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
         74: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
         73: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
         72: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:37:in `start'
         71: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
         70: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
         69: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
         68: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
         67: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
         66: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
         65: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
         64: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
         63: from config.ru:3:in `block in <main>'
         62: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
         61: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
         60: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
         59: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
         58: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         57: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         56: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         55: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         54: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         53: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         52: from /home/ndinfo/property/config/environment.rb:5:in `<main>'
         51: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
         50: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
         49: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
         48: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
         47: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
         46: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
         45: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
         44: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
         43: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
         42: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
         41: from /home/ndinfo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
         40: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
         39: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
         38: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
         37: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
         36: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:10:in `execute'
         35: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/file_update_checker.rb:83:in `execute'
         34: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:29:in `block in updater'
         33: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:20:in `reload!'
         32: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
         31: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `each'
         30: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
         29: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
         28: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
         27: from /home/ndinfo/property/config/routes.rb:1:in `<main>'
         26: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:408:in `draw'
         25: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
         24: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
         23: from /home/ndinfo/property/config/routes.rb:3:in `block in <main>'
         22: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/rails/routes.rb:242:in `devise_for'
         21: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/rails/routes.rb:242:in `each'
         20: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/rails/routes.rb:243:in `block in devise_for'
         19: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise.rb:346:in `add_mapping'
         18: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise.rb:346:in `new'
         17: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/mapping.rb:72:in `initialize'
         16: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/mapping.rb:162:in `default_used_route'
         15: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/mapping.rb:95:in `routes'
         14: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/mapping.rb:78:in `modules'
         13: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise/mapping.rb:83:in `to'
         12: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/devise-4.7.3/lib/devise.rb:316:in `get'
         11: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
         10: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:280:in `constantize'
          9: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:280:in `inject'
          8: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:280:in `each'
          7: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:282:in `block in constantize'
          6: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:282:in `const_get'
          5: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
          4: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
          3: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
          2: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
          1: from /home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ndinfo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': /home/ndinfo/property/app/models/account.rb:5: syntax error, unexpected ':', expecting end (SyntaxError)
..., :rememberable, :validatable :trackable, :confirmable
```

**Comment by casperisfine** [comment]
This is a syntax error in your code, not a problem in bugsnag:

```
/home/ndinfo/property/app/models/account.rb:5: syntax error, unexpected ':', expecting end (SyntaxError)
```
