### ISSUE TITLE
Error on Apple M1

### ISSUE THREAD

**Issue by mintotsai** [Shopify/bootsnap#352]
Hi,

I'm getting an error when running on an Apple M1 with Ruby 3.0.0 and Rails 6.1.3.1. Is this a known issue or did I miss a step? Thanks.

```
% foreman start      
07:02:18 backend.1  | started with pid 12059
07:02:18 frontend.1 | started with pid 12060
07:02:19 backend.1  | /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': dlopen(/Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/bootsnap.bundle, 9): no suitable image found.  Did find: (LoadError)
07:02:19 backend.1  |   /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/bootsnap.bundle: mach-o, but wrong architecture
07:02:19 backend.1  |   /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/bootsnap.bundle: stat() failed with errno=25 - /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/bootsnap.bundle
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/compile_cache/iseq.rb:2:in `<top (required)>'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/compile_cache.rb:10:in `setup'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap.rb:67:in `setup'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap.rb:108:in `default_setup'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/setup.rb:4:in `<top (required)>'
07:02:19 backend.1  |   from /Users/mintotsai/Programming/rails.my/jasmine_reboot/config/boot.rb:4:in `require'
07:02:19 backend.1  |   from /Users/mintotsai/Programming/rails.my/jasmine_reboot/config/boot.rb:4:in `<top (required)>'
07:02:19 backend.1  |   from /Users/mintotsai/Programming/rails.my/jasmine_reboot/bin/rails:8:in `require_relative'
07:02:19 backend.1  |   from /Users/mintotsai/Programming/rails.my/jasmine_reboot/bin/rails:8:in `<top (required)>'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
07:02:19 backend.1  |   from /Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
07:02:19 backend.1  |   from <internal:/Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
07:02:19 backend.1  |   from <internal:/Users/mintotsai/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
07:02:19 backend.1  |   from /Users/mintotsai/Programming/rails.my/jasmine_reboot/bin/spring:15:in `<top (required)>'
07:02:19 backend.1  |   from bin/rails:3:in `load'
07:02:19 backend.1  |   from bin/rails:3:in `<main>'
07:02:19 frontend.1 | ℹ ｢wds｣: Project is running at http://localhost:3035/
07:02:19 frontend.1 | ℹ ｢wds｣: webpack output is served from /packs/
07:02:19 frontend.1 | ℹ ｢wds｣: Content not from webpack is served from /Users/mintotsai/Programming/rails.my/jasmine_reboot/public/packs
07:02:19 frontend.1 | ℹ ｢wds｣: 404s will fallback to /index.html
07:02:19 backend.1  | exited with code 1
07:02:19 system     | sending SIGTERM to all processes
^C07:02:24 system     | sending SIGKILL to all processes
```

**Comment by casperisfine** [comment]
Weird. Was bootsnap compiled on this machine? Or was it somehow migrated from an older intel mac?

Can you try uninstalling/reinstalling bootsnap?

**Comment by mintotsai** [comment]
After completely uninstalling brew and reinstalling, it all seems to be working now.

Apologies for the false alarm.
