### ISSUE TITLE
Disable Compile Cache C Error

### ISSUE THREAD

**Issue by metaskills** [Shopify/bootsnap#356]
While working on #355 I was exploring setting the `DISABLE_BOOTSNAP_COMPILE_CACHE` to see how only the load path optimizations might work. When doing this, I get the following error.

```
undefined method `instrumentation_enabled=' for Bootsnap:Module\nDid you mean?  instrumentation=
Init<NoMethodError>
"/var/task/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.4/lib/bootsnap.rb:30:in `instrumentation='",
"/var/task/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.4/lib/bootsnap.rb:24:in `logger='",
"/var/task/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.4/lib/bootsnap.rb:16:in `log!'",
"/var/task/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.4/lib/bootsnap.rb:117:in `default_setup'",
"/var/task/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.4/lib/bootsnap/setup.rb:4:in `<top (required)>'",
"/var/task/app.rb:14:in `require'",
"/var/task/app.rb:14:in `<top (required)>'",
"/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
"/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'"
```

**Comment by casperisfine** [comment]
It seems you need `BOOTSNAP_LOG=1` as well to trigger this. It's because the logging method didn't account for bootsnap to be mostly disabled. I'll fix this directly on master. Thanks for the report.

**Comment by metaskills** [comment]
> It seems you need BOOTSNAP_LOG=1 as well to trigger this.

Correct! I was using that. Think this is worth a v1.7.5 release?

**Comment by metaskills** [comment]
Cool, I'll wait for a release till I pull my patches out. Thanks.
