### ISSUE TITLE
Rails console failed with cannot load irb/color_printer

### ISSUE THREAD

**Issue by msa7** [Shopify/bootsnap#363]
Rails console failed in production env with

```
Loading production environment (Rails 6.1.3.2)
/ruby_gems/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- irb/color_printer (LoadError)
Did you mean?  irb/color_printer
	from /ruby_gems/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /usr/local/lib/ruby/3.0.0/irb/inspector.rb:117:in `block in <module:IRB>'
	from /usr/local/lib/ruby/3.0.0/irb/inspector.rb:97:in `init'
```

Comment out `require 'bootsnap/setup'` in `config/boot.rb` fix the Rails console.

**Comment by casperisfine** [comment]
Could you provide a reproduction script please?

**Comment by casperisfine** [comment]
Also any chance it could be related to https://github.com/rails/rails/issues/42373?
