### ISSUE TITLE
"deadlock; recursive locking" ThreadError unless I delete the cache for every execution

### ISSUE THREAD

**Issue by fdr** [Shopify/bootsnap#404]
### I made sure the issue is in bootsnap

Probably. I've been using it for a while and it has worked well until an upgrade. It's possible I was relying on a bug before, but this doesn't seem to affect my colleagues on Macintosh.

### Steps to reproduce

Not entirely sure, but I can tell you it didn't happen in 1.9.3 but does happen in 1.10.2 (I could bisect it for you if you have some good steps to use arbitrary bootsnap versions).

### Expected behavior

I should be able to start programs.

### Actual behavior

I get this stack trace upon starting programs:

```
/home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/cache.rb:58:in `synchronize': deadlock; recursive locking (ThreadError)
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/cache.rb:58:in `find'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:12:in `require'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/store.rb:92:in `dump_data'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/store.rb:64:in `commit_transaction'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/store.rb:55:in `block in transaction'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/store.rb:51:in `synchronize'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/store.rb:51:in `transaction'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/cache.rb:155:in `unshift_paths_locked'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/cache.rb:106:in `block in unshift_paths'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/cache.rb:106:in `synchronize'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/cache.rb:106:in `unshift_paths'
	from /home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/change_observer.rb:22:in `unshift'
	from /home/fdr/code/owl/config/boot.rb:19:in `<top (required)>'
	from /home/fdr/code/owl/config/environment.rb:4:in `require_relative'
	from /home/fdr/code/owl/config/environment.rb:4:in `<top (required)>'
	from /home/fdr/code/owl/lib/console.rb:7:in `require_relative'
	from /home/fdr/code/owl/lib/console.rb:7:in `block in <top (required)>'
	from <internal:kernel>:90:in `tap'
	from /home/fdr/code/owl/lib/console.rb:6:in `<top (required)>'
	from bin/irb:4:in `load'
	from bin/irb:4:in `<main>'
```

I do have a workaround, which I must use to start any program:

```sh
rm -rf tmp/cache/ && bundle exec dotenv bin/irb
[works normally]
```

Oddly, setting `DISABLE_BOOTSNAP` doesn't do the trick.

```sh
DISABLE_BOOTSNAP=1 bundle exec dotenv bin/irb
/home/fdr/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/cache.rb:58:in `synchronize': deadlock; recursive locking (ThreadError)
[...]
```
### System configuration

**Bootsnap version**:
1.10.2
**Ruby version**:
3.0.3
**Rails version**: 
Not a rails program.

I'm on Fedora Linux, by the way.

**Comment by fdr** [comment]
I have aliased removing the cache directory to start programs still. Continues with Ruby 3.1.1.

**Comment by casperisfine** [comment]
also in the meantime a quick workaround would be to add `require "fileutils"` before to setup bootsnap.
