### ISSUE TITLE
hangs on Debian ppc64el

### ISSUE THREAD

**Issue by terceiro** [Shopify/bootsnap#415]
When running the bootsnap test suite on the Debian ppc64el architecture, some tests will cause bootsnap to hang forever.  One can reproduce this with, for example, `Bootsnap::CLITest#test_precompile_gemfile`. I can reproduce this with both ruby3.0 and ruby3.1, but only on ppc64el. No other official Debian architecture is affected.

### Steps to reproduce

1. Download the "ppc64el-pseries" qemu images from https://people.debian.org/~gio/dqib/.
2. Unzip the contents, cd into the generated directory
3. Boot the image with this command line: `qemu-system-ppc64le -machine pseries -cpu power9 -m 4G -smp 2 -drive file=image.qcow2 -device e1000,netdev=net -netdev user,id=net,hostfwd=tcp::2222-:22 -kernel kernel -initrd initrd -nographic -append "root=LABEL=rootfs console=hvc0"`
4. Login as root, password "root"
5. `apt-get update && apt-get install -qy ruby-dev git`
6. `git clone https://github.com/Shopify/bootsnap.git`
7. `cd bootsnap`
8. `bundle install`
9. `bundle exec rake TESTOPTS='-v -ntest_precompile_gemfile'`

(ruby3.0 is currently the default. to reproduce with ruby3,1, install `ruby3.1-dev`, and use `bundle3.1` instead of just `bundle` in the command lines above).

the output looks like this:

```
# bundle exec rake TESTOPTS='-v -ntest_precompile_gemfile'
/usr/bin/gmake install target_prefix=
/usr/bin/install -c -m 0755 bootsnap.so /root/bootsnap/lib/bootsnap
cp tmp/powerpc64le-linux-gnu/bootsnap/3.0.4/bootsnap.so tmp/powerpc64le-linux-gnu/stage/lib/bootsnap/bootsnap.so
Run options: -v -ntest_precompile_gemfile --seed 52554

# Running:

Bootsnap::CLITest#test_precompile_gemfile = 
```

(and stays there forever, until I interrupt with a control-c; but even then there are multiple processed left behind that I need to kill manually)

**Bootsnap version**: from git
**Ruby version**: 3.0 or 3.1

**Comment by casperisfine** [comment]
Thanks for the report, that's intriguing.

If you wish to debug this further, I'd suggest trying to get a Ruby backtrace from these sub processes. 

A cheap way to do this is to spawn a thread that periodically dump the main thread backtrace:

```ruby
Thread.new { loop { File.write("/tmp/ruby-#{$$}.log", Thread.main.backtrace.join("\n")); sleep 1 } }
```

If you inject this right after the `fork` call, it should give you an idea.

I'll see if I find time to do this myself, but no promises.

Also it's quite likely that you just uncovered a bug in Ruby.

**Comment by terceiro** [comment]
something else that feels weird is that temporary directories left over from those tests look quite big:

```
$ du -shc /tmp/bootsnap-test2022051*
12M	/tmp/bootsnap-test20220510-20661-te6zrm
140M	/tmp/bootsnap-test20220511-23438-zirpy5
140M	/tmp/bootsnap-test20220511-25624-3o4l2o
140M	/tmp/bootsnap-test20220511-25726-v7x5r1
136M	/tmp/bootsnap-test20220511-27487-jnhkaa
136M	/tmp/bootsnap-test20220511-27556-b0p4d9
701M	total
```

I don't know if this data point is useful, as I didn't study the bootsnap internals yet, I'm just trying to handle the fallout from a new ruby version. :) But when I run the full test suite on my local machine (x86_64), all of those temporary directories are a few hundred KB.

**Comment by casperisfine** [comment]
Ok, so most workers are stuck on `/home/terceiro/bootsnap/lib/bootsnap/cli/worker_pool.rb:64:in `binmode'`, which is expected, they're just waiting for the master process to give them work.

One however is stuck on `/home/terceiro/bootsnap/lib/bootsnap/compile_cache/iseq.rb:29:in `compile_file'`, which is a call to `RubyVM::InstructionSequence.compile_file`, which seem to match my suspicion of a Ruby bug.

As a next step I'd suggest to add some print in there to see which file it's trying to compile, if it's consistent that should allow to reduce the reproduction step to just `RubyVM::InstructionSequence.compile_file("path/to/file.rb")`.

> something else that feels weird is that temporary directories left over from those tests look quite big:

Yes, what's way too much, that's another indication that it might be a bug in `compile_file`, something must cause it to generate way more bytecode than it should.
