### ISSUE TITLE
Bootsnap LoadError for Prism 

### ISSUE THREAD

**Issue by bparanj** [Shopify/bootsnap#463]
### Steps to reproduce

bug_report.rb:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "bootsnap"
end

ENV["BOOTSNAP_CACHE_DIR"] = "bootsnap_cache"
require "bootsnap/setup"

require "prism"
```

### Expected behavior

It should load the prism gem that is now part of Ruby 3.3.0 standard library. Any environment other than development results in error.

### Actual behavior

```
RAILS_ENV=test ruby bug.rb
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require': cannot load such file -- prism/prism (LoadError)
	from /home/ubuntu/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/prism.rb:96:in `<main>'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bug.rb:14:in `<main>'
```

### System configuration

**Bootsnap version**: 1.17.0

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

**Rails version**: Rails 7.1.2

**Comment by casperisfine** [comment]
```c
void
Init_Prism(void)
{
    ruby_init_ext("prism/prism.so", Init_prism);
}
```

```c
// Private API for statically linked extensions.
// Used with the ext/Setup file, the --with-setup and
// --with-static-linked-ext configuration option, etc.
void
ruby_init_ext(const char *name, void (*init)(void))
{
    st_table *inits_table;
    rb_vm_t *vm = GET_VM();

    if (feature_provided(vm, name, 0))
        return;

    inits_table = vm->static_ext_inits;
    if (!inits_table) {
        inits_table = st_init_strtable();
        vm->static_ext_inits = inits_table;
    }
    st_update(inits_table, (st_data_t)name, register_init_ext, (st_data_t)init);
}
```

So as I suspected, `prism.so` doesn't actually exist, Ruby simply pretend it does.

**Comment by kddnewton** [comment]
@casperisfine anything you need from me on this? Looks like you solved it.
