### ISSUE TITLE
cannot load such file : thread.bundle (LoadError)

### ISSUE THREAD

**Issue by benoittgt** [Shopify/bootsnap#6]
Hello

Thanks for this project. I tried to use it: 

```ruby
#gemfile
group :development, :test do
  gem 'bootsnap', require: false

# boot.rb
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap'
Bootsnap.setup(
  cache_dir:            'tmp/cache', # Path to your cache
  development_mode:     ENV['MY_ENV'] == 'development',
  load_path_cache:      true,        # Should we optimize the LOAD_PATH with a cache?
  autoload_paths_cache: true,        # Should we optimize ActiveSupport autoloads with cache?
  disable_trace:        false,       # Sets `RubyVM::InstructionSequence.compile_option = { trace_instruction: false }`
  compile_cache_iseq:   true,        # Should compile Ruby code into ISeq cache?
  compile_cache_yaml:   true         # Should compile YAML into a cache?
)

require 'rails/commands/server'
module Rails
  class Server
    def default_options
      super.merge(Host:  '0.0.0.0', Port: 3000)
    end
  end
end
```

```
/Users/bti/.rvm/gems/ruby-2.4.1@appaloosa/gems/bootsnap-0.2.0/lib/bootsnap/explicit_require.rb:16:in `require': cannot load such file -- /Users/bti/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/x86_64-darwin16/thread.bundle (LoadError)
	from /Users/bti/.rvm/gems/ruby-2.4.1@appaloosa/gems/bootsnap-0.2.0/lib/bootsnap/explicit_require.rb:16:in `from_archdir'
	from /Users/bti/.rvm/gems/ruby-2.4.1@appaloosa/gems/bootsnap-0.2.0/lib/bootsnap/load_path_cache/cache.rb:3:in `<top (required)>'
	from /Users/bti/.rvm/gems/ruby-2.4.1@appaloosa/gems/bootsnap-0.2.0/lib/bootsnap/load_path_cache.rb:50:in `require_relative'
	from /Users/bti/.rvm/gems/ruby-2.4.1@appaloosa/gems/bootsnap-0.2.0/lib/bootsnap/load_path_cache.rb:50:in `<top (required)>'
	from /Users/bti/.rvm/gems/ruby-2.4.1@appaloosa/gems/bootsnap-0.2.0/lib/bootsnap.rb:2:in `require_relative'
	from /Users/bti/.rvm/gems/ruby-2.4.1@appaloosa/gems/bootsnap-0.2.0/lib/bootsnap.rb:2:in `<top (required)>'
	from /Users/bti/code/appaloosa/config/boot.rb:4:in `require'
	from /Users/bti/code/appaloosa/config/boot.rb:4:in `<top (required)>'
	from /Users/bti/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/bti/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from bin/rails:5:in `<main>'
```

I tried different way of using it (loading it in gemfile without `require: false`), replacing require `bootsnap` with `BootLib::Require.from_gem('bootsnap', 'bootsnap')` but it will then raise : 

```
/Users/bti/code/appaloosa/config/boot.rb:4:in `<top (required)>': uninitialized constant BootLib (NameError)
	from /Users/bti/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/bti/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from bin/rails:5:in `<main>'
```

**Comment by burke** [comment]
Interesting. What's the result of this?

```ruby
$:.select{|f|File.exist?("#{f}/thread.bundle")}
```

**Comment by lest** [comment]
I have the same issue with Ruby 2.4.1.

I'm getting the following results:

```
[1] pry(main)> $:.select{|f|File.exist?("#{f}/thread.bundle")}
=> []
[2] pry(main)> RbConfig::CONFIG.select{|_,v|$:.include?(v)}
=> {"vendorarchdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/vendor_ruby/2.4.0/x86_64-darwin16",
 "vendorlibdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/vendor_ruby/2.4.0",
 "vendordir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/vendor_ruby",
 "sitearchdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/x86_64-darwin16",
 "sitelibdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0",
 "sitedir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/site_ruby",
 "rubyarchdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16",
 "rubylibdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/2.4.0",
 "archdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16",
 "topdir"=>"/Users/lest/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16"}
```

I also searched `thread.bundle` and it present only for Ruby 2.3.3 on my machine:

```
➜  ~ ls -l ~/.rbenv/versions
total 0
drwxr-xr-x  6 lest  staff  204 Jan  2 21:36 2.3.3
drwxr-xr-x  6 lest  staff  204 Mar 24 10:17 2.4.1
➜  ~ find ~/.rbenv/versions -name 'thread.bundle'
/Users/lest/.rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-darwin16/thread.bundle
```

**Comment by burke** [comment]
ah, drat, 2.4 probably just builds it in or something. I'll install it and push a fix in a few minutes.

**Comment by burke** [comment]
Fixed by 49a8447ab96e30dd8f18b9f2f8dd8d93ebc242d0, thanks!

**Comment by burke** [comment]
If someone can try specifying that as a git sha in their Gemfile and let me know whether it works, I'll push 0.2.1 if it's good now.

**Comment by lest** [comment]
@burke I'm getting the following error:

```
/Users/lest/code/myapp/vendor/bundle/ruby/2.4.0/bundler/gems/bootsnap-49a8447ab96e/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require': cannot load such file -- thread (LoadError)
        from /Users/lest/code/myapp/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:2:in `<top (required)>'
        from /Users/lest/code/myapp/vendor/bundle/ruby/2.4.0/bundler/gems/bootsnap-49a8447ab96e/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/lest/code/myapp/vendor/bundle/ruby/2.4.0/bundler/gems/bootsnap-49a8447ab96e/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/lest/code/myapp/vendor/bundle/ruby/2.4.0/bundler/gems/bootsnap-49a8447ab96e/lib/bootsnap/load_path_cache.rb:35:in `setup'
        from /Users/lest/code/myapp/vendor/bundle/ruby/2.4.0/bundler/gems/bootsnap-49a8447ab96e/lib/bootsnap.rb:23:in `setup'
        from /Users/lest/code/myapp/config/boot.rb:9:in `<top (required)>'
        from /Users/lest/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/lest/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from script/rails:5:in `<main>'
```

**Comment by burke** [comment]
Oh yeah, try 3f73407b8ff64095aace0b0c5c9d7d4fd2a2b409

**Comment by lest** [comment]
@burke All is good now! Thank you!

**Comment by burke** [comment]
0.2.1 pushed. Thanks!

**Comment by benoittgt** [comment]
Thanks for the quick changes !

**Comment by fnicola** [comment]
@burke I am getting /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-
```
1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant GeoKit (NameError)
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:11:in `block in with_bootsnap_fallback'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `without_bootsnap_cache'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:11:in `rescue in with_bootsnap_fallback'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
	from /Users/nicola/workspace/bookingbug/vendor/plugins/geokit-rails/lib/geokit-rails.rb:16:in `<main>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/nicola/workspace/bookingbug/vendor/plugins/geokit-rails/init.rb:2:in `block in <class:Plugin>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/plugin.rb:82:in `eval'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/plugin.rb:82:in `block in <class:Plugin>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `each'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/nicola/workspace/bookingbug/config/environment.rb:48:in `<main>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/nicola/workspace/bookingbug/config.ru:3:in `block in <main>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
	from /Users/nicola/workspace/bookingbug/config.ru:in `new'
	from /Users/nicola/workspace/bookingbug/config.ru:in `<main>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/rack-1.4.7/lib/rack/server.rb:200:in `app'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands/server.rb:46:in `app'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/rack-1.4.7/lib/rack/server.rb:304:in `wrapped_app'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/rack-1.4.7/lib/rack/server.rb:254:in `start'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands/server.rb:70:in `start'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands.rb:55:in `block in <main>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands.rb:50:in `tap'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands.rb:50:in `<main>'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/nicola/.rvm/gems/ruby-2.3.3/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from script/rails:6:in `<main>'
```

**Comment by rohanmandhanya** [comment]
@burke Hi I am also having the trouble for the GSL.
LoadError: cannot load such file -- gsl
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
<main>:2:in `<main>'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/backend.rb:44:in `eval'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/backend.rb:44:in `eval'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/backend.rb:12:in `eval'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/kernel.rb:87:in `execute_request'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/kernel.rb:47:in `dispatch'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/kernel.rb:37:in `run'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `run_kernel'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
/Users/rohan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/Users/rohan/.rbenv/versions/2.4.1/bin/iruby:22:in `load'
/Users/rohan/.rbenv/versions/2.4.1/bin/iruby:22:in `<main>'

Can you please help me with the error.
