### ISSUE TITLE
undefined method `instance' for ActiveSupport::Deprecation:Class (NoMethodError)

### ISSUE THREAD

**Issue by hudsonsferreira** [Shopify/bootsnap#95]
HI guys, I'm trying it out and got this exception:

Gemfile:
```ruby 
gem 'bootsnap', require: false
```

config/boot.rb
```ruby
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup'
```

Full stack trace:
```
➜ rails s
/Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:124:in `initialize': undefined method `instance' for ActiveSupport::Deprecation:Class (NoMethodError)
Did you mean?  instance_of?
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/load_error.rb:30:in `<top (required)>'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:12:in `<top (required)>'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache.rb:35:in `setup'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.5/lib/bootsnap.rb:23:in `setup'
	from /Users/hudsonferreira/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootsnap-1.1.5/lib/bootsnap/setup.rb:39:in `<top (required)>'
	from /Users/hudsonferreira/Development/indeva/web/config/boot.rb:4:in `require'
	from /Users/hudsonferreira/Development/indeva/web/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

Ruby version: 2.3.1
Rails version: 5.0.0.1

Regards!

**Comment by rafaelfranca** [comment]
You likely found a bug in Rails already fixed on the latest release of 5.0 series. Can you try to upgrade your rails application to 5.0.6?

**Comment by hudsonsferreira** [comment]
thanks for reply @rafaelfranca we are already migrating to rails 5.1.4 :) should we consider to add this info on README?

**Comment by rafaelfranca** [comment]
I don't think so. It is a bug in Rails and has nothing to do with bootsnap, so there is no need to bootsnap talk about an old version of rails that we know have bugs.

**Comment by rafaelfranca** [comment]
Can you confirm this issue is fixed upgrading the rails version to 5.0.6?

**Comment by hudsonsferreira** [comment]
@rafaelfranca yep it is

**Comment by rafaelfranca** [comment]
Thanks!
